// profile.proto — 玩家档案 + 卡组（云存档）
//
// V4-S2：客户端切到在线模式时从此读档；改卡组经 DeckUpdateReq 推回。
// version 字段用于乐观锁：服务端版本胜出，客户端版本旧 -> 服务端回最新档。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: profile.proto

package profile

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 完整档案（比 ProfileSummary 多 exp/season/version/updated_at）。
type Profile struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccountId       int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Nickname        string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	AvatarId        int32                  `protobuf:"varint,3,opt,name=avatar_id,json=avatarId,proto3" json:"avatar_id,omitempty"`
	Level           int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	Exp             int32                  `protobuf:"varint,5,opt,name=exp,proto3" json:"exp,omitempty"`
	Trophies        int32                  `protobuf:"varint,6,opt,name=trophies,proto3" json:"trophies,omitempty"`
	CurrentSeasonId int32                  `protobuf:"varint,7,opt,name=current_season_id,json=currentSeasonId,proto3" json:"current_season_id,omitempty"`
	Version         int32                  `protobuf:"varint,8,opt,name=version,proto3" json:"version,omitempty"`                      // 乐观锁版本
	UpdatedAt       int64                  `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // unix seconds
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{0}
}

func (x *Profile) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *Profile) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *Profile) GetAvatarId() int32 {
	if x != nil {
		return x.AvatarId
	}
	return 0
}

func (x *Profile) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Profile) GetExp() int32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *Profile) GetTrophies() int32 {
	if x != nil {
		return x.Trophies
	}
	return 0
}

func (x *Profile) GetCurrentSeasonId() int32 {
	if x != nil {
		return x.CurrentSeasonId
	}
	return 0
}

func (x *Profile) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Profile) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type Deck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Slot          int32                  `protobuf:"varint,2,opt,name=slot,proto3" json:"slot,omitempty"`                     // 1..3
	CardIds       []string               `protobuf:"bytes,3,rep,name=card_ids,json=cardIds,proto3" json:"card_ids,omitempty"` // 8 个 card_id（与 V3 cards.json id 同源）
	IsActive      bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Deck) Reset() {
	*x = Deck{}
	mi := &file_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deck) ProtoMessage() {}

func (x *Deck) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deck.ProtoReflect.Descriptor instead.
func (*Deck) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{1}
}

func (x *Deck) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Deck) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *Deck) GetCardIds() []string {
	if x != nil {
		return x.CardIds
	}
	return nil
}

func (x *Deck) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

// 玩家档案 + 全部卡组 + 解锁卡集合。
// unlocks 字段 V4 玩法验证阶段默认 "全卡解锁"（客户端按这个判可组卡）；
// 等 V4-S10 IAP/养成接入后才有意义的差异化。
type ProfileGetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileGetReq) Reset() {
	*x = ProfileGetReq{}
	mi := &file_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileGetReq) ProtoMessage() {}

func (x *ProfileGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileGetReq.ProtoReflect.Descriptor instead.
func (*ProfileGetReq) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{2}
}

type ProfileGetResp struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Profile         *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Decks           []*Deck                `protobuf:"bytes,2,rep,name=decks,proto3" json:"decks,omitempty"`
	UnlockedCardIds []string               `protobuf:"bytes,3,rep,name=unlocked_card_ids,json=unlockedCardIds,proto3" json:"unlocked_card_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProfileGetResp) Reset() {
	*x = ProfileGetResp{}
	mi := &file_profile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileGetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileGetResp) ProtoMessage() {}

func (x *ProfileGetResp) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileGetResp.ProtoReflect.Descriptor instead.
func (*ProfileGetResp) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{3}
}

func (x *ProfileGetResp) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *ProfileGetResp) GetDecks() []*Deck {
	if x != nil {
		return x.Decks
	}
	return nil
}

func (x *ProfileGetResp) GetUnlockedCardIds() []string {
	if x != nil {
		return x.UnlockedCardIds
	}
	return nil
}

type DeckUpdateReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Slot            int32                  `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	CardIds         []string               `protobuf:"bytes,2,rep,name=card_ids,json=cardIds,proto3" json:"card_ids,omitempty"`
	SetActive       bool                   `protobuf:"varint,3,opt,name=set_active,json=setActive,proto3" json:"set_active,omitempty"`
	ExpectedVersion int32                  `protobuf:"varint,4,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"` // 客户端持有的 profile.version（乐观锁）
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeckUpdateReq) Reset() {
	*x = DeckUpdateReq{}
	mi := &file_profile_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeckUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeckUpdateReq) ProtoMessage() {}

func (x *DeckUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeckUpdateReq.ProtoReflect.Descriptor instead.
func (*DeckUpdateReq) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{4}
}

func (x *DeckUpdateReq) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *DeckUpdateReq) GetCardIds() []string {
	if x != nil {
		return x.CardIds
	}
	return nil
}

func (x *DeckUpdateReq) GetSetActive() bool {
	if x != nil {
		return x.SetActive
	}
	return false
}

func (x *DeckUpdateReq) GetExpectedVersion() int32 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

type DeckUpdateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	NewVersion    int32                  `protobuf:"varint,2,opt,name=new_version,json=newVersion,proto3" json:"new_version,omitempty"` // 写后版本（客户端更新本地缓存）
	Profile       *Profile               `protobuf:"bytes,3,opt,name=profile,proto3" json:"profile,omitempty"`                          // 顺带回 profile（节省一次 GET）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeckUpdateResp) Reset() {
	*x = DeckUpdateResp{}
	mi := &file_profile_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeckUpdateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeckUpdateResp) ProtoMessage() {}

func (x *DeckUpdateResp) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeckUpdateResp.ProtoReflect.Descriptor instead.
func (*DeckUpdateResp) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{5}
}

func (x *DeckUpdateResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *DeckUpdateResp) GetNewVersion() int32 {
	if x != nil {
		return x.NewVersion
	}
	return 0
}

func (x *DeckUpdateResp) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

var File_profile_proto protoreflect.FileDescriptor

const file_profile_proto_rawDesc = "" +
	"\n" +
	"\rprofile.proto\x12\agame.v4\"\x8a\x02\n" +
	"\aProfile\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x1b\n" +
	"\tavatar_id\x18\x03 \x01(\x05R\bavatarId\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\x12\x10\n" +
	"\x03exp\x18\x05 \x01(\x05R\x03exp\x12\x1a\n" +
	"\btrophies\x18\x06 \x01(\x05R\btrophies\x12*\n" +
	"\x11current_season_id\x18\a \x01(\x05R\x0fcurrentSeasonId\x12\x18\n" +
	"\aversion\x18\b \x01(\x05R\aversion\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\x03R\tupdatedAt\"b\n" +
	"\x04Deck\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04slot\x18\x02 \x01(\x05R\x04slot\x12\x19\n" +
	"\bcard_ids\x18\x03 \x03(\tR\acardIds\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\"\x0f\n" +
	"\rProfileGetReq\"\x8d\x01\n" +
	"\x0eProfileGetResp\x12*\n" +
	"\aprofile\x18\x01 \x01(\v2\x10.game.v4.ProfileR\aprofile\x12#\n" +
	"\x05decks\x18\x02 \x03(\v2\r.game.v4.DeckR\x05decks\x12*\n" +
	"\x11unlocked_card_ids\x18\x03 \x03(\tR\x0funlockedCardIds\"\x88\x01\n" +
	"\rDeckUpdateReq\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x05R\x04slot\x12\x19\n" +
	"\bcard_ids\x18\x02 \x03(\tR\acardIds\x12\x1d\n" +
	"\n" +
	"set_active\x18\x03 \x01(\bR\tsetActive\x12)\n" +
	"\x10expected_version\x18\x04 \x01(\x05R\x0fexpectedVersion\"m\n" +
	"\x0eDeckUpdateResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1f\n" +
	"\vnew_version\x18\x02 \x01(\x05R\n" +
	"newVersion\x12*\n" +
	"\aprofile\x18\x03 \x01(\v2\x10.game.v4.ProfileR\aprofileBBZ@github.com/jchensh/godot-clash-pusher/server/internal/pb/profileb\x06proto3"

var (
	file_profile_proto_rawDescOnce sync.Once
	file_profile_proto_rawDescData []byte
)

func file_profile_proto_rawDescGZIP() []byte {
	file_profile_proto_rawDescOnce.Do(func() {
		file_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_profile_proto_rawDesc), len(file_profile_proto_rawDesc)))
	})
	return file_profile_proto_rawDescData
}

var file_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_profile_proto_goTypes = []any{
	(*Profile)(nil),        // 0: game.v4.Profile
	(*Deck)(nil),           // 1: game.v4.Deck
	(*ProfileGetReq)(nil),  // 2: game.v4.ProfileGetReq
	(*ProfileGetResp)(nil), // 3: game.v4.ProfileGetResp
	(*DeckUpdateReq)(nil),  // 4: game.v4.DeckUpdateReq
	(*DeckUpdateResp)(nil), // 5: game.v4.DeckUpdateResp
}
var file_profile_proto_depIdxs = []int32{
	0, // 0: game.v4.ProfileGetResp.profile:type_name -> game.v4.Profile
	1, // 1: game.v4.ProfileGetResp.decks:type_name -> game.v4.Deck
	0, // 2: game.v4.DeckUpdateResp.profile:type_name -> game.v4.Profile
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_profile_proto_init() }
func file_profile_proto_init() {
	if File_profile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_profile_proto_rawDesc), len(file_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_profile_proto_goTypes,
		DependencyIndexes: file_profile_proto_depIdxs,
		MessageInfos:      file_profile_proto_msgTypes,
	}.Build()
	File_profile_proto = out.File
	file_profile_proto_goTypes = nil
	file_profile_proto_depIdxs = nil
}
