// leaderboard.proto — 赛季排行榜
//
// V4-S5：Redis ZSET 实时存读。
//   - 全球榜：leaderboard:global:s<season_id>
//   - 段位榜：leaderboard:arena:<arena>:s<season_id>
// 客户端不订阅、按需轮询拉。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: leaderboard.proto

package leaderboard

import (
	common "github.com/jchensh/godot-clash-pusher/server/internal/pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LeaderboardTopReq_Scope int32

const (
	LeaderboardTopReq_GLOBAL LeaderboardTopReq_Scope = 0
	LeaderboardTopReq_ARENA  LeaderboardTopReq_Scope = 1
)

// Enum value maps for LeaderboardTopReq_Scope.
var (
	LeaderboardTopReq_Scope_name = map[int32]string{
		0: "GLOBAL",
		1: "ARENA",
	}
	LeaderboardTopReq_Scope_value = map[string]int32{
		"GLOBAL": 0,
		"ARENA":  1,
	}
)

func (x LeaderboardTopReq_Scope) Enum() *LeaderboardTopReq_Scope {
	p := new(LeaderboardTopReq_Scope)
	*p = x
	return p
}

func (x LeaderboardTopReq_Scope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LeaderboardTopReq_Scope) Descriptor() protoreflect.EnumDescriptor {
	return file_leaderboard_proto_enumTypes[0].Descriptor()
}

func (LeaderboardTopReq_Scope) Type() protoreflect.EnumType {
	return &file_leaderboard_proto_enumTypes[0]
}

func (x LeaderboardTopReq_Scope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LeaderboardTopReq_Scope.Descriptor instead.
func (LeaderboardTopReq_Scope) EnumDescriptor() ([]byte, []int) {
	return file_leaderboard_proto_rawDescGZIP(), []int{0, 0}
}

type LeaderboardTopReq struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Scope         LeaderboardTopReq_Scope `protobuf:"varint,1,opt,name=scope,proto3,enum=game.v4.LeaderboardTopReq_Scope" json:"scope,omitempty"`
	SeasonId      int32                   `protobuf:"varint,2,opt,name=season_id,json=seasonId,proto3" json:"season_id,omitempty"` // 0 = 当前赛季
	Arena         int32                   `protobuf:"varint,3,opt,name=arena,proto3" json:"arena,omitempty"`                       // scope=ARENA 时必填
	Limit         int32                   `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`                       // 1..100
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardTopReq) Reset() {
	*x = LeaderboardTopReq{}
	mi := &file_leaderboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardTopReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardTopReq) ProtoMessage() {}

func (x *LeaderboardTopReq) ProtoReflect() protoreflect.Message {
	mi := &file_leaderboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardTopReq.ProtoReflect.Descriptor instead.
func (*LeaderboardTopReq) Descriptor() ([]byte, []int) {
	return file_leaderboard_proto_rawDescGZIP(), []int{0}
}

func (x *LeaderboardTopReq) GetScope() LeaderboardTopReq_Scope {
	if x != nil {
		return x.Scope
	}
	return LeaderboardTopReq_GLOBAL
}

func (x *LeaderboardTopReq) GetSeasonId() int32 {
	if x != nil {
		return x.SeasonId
	}
	return 0
}

func (x *LeaderboardTopReq) GetArena() int32 {
	if x != nil {
		return x.Arena
	}
	return 0
}

func (x *LeaderboardTopReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type LeaderboardEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rank          int32                  `protobuf:"varint,1,opt,name=rank,proto3" json:"rank,omitempty"`
	Profile       *common.ProfileSummary `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`
	Trophies      int32                  `protobuf:"varint,3,opt,name=trophies,proto3" json:"trophies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardEntry) Reset() {
	*x = LeaderboardEntry{}
	mi := &file_leaderboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardEntry) ProtoMessage() {}

func (x *LeaderboardEntry) ProtoReflect() protoreflect.Message {
	mi := &file_leaderboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardEntry.ProtoReflect.Descriptor instead.
func (*LeaderboardEntry) Descriptor() ([]byte, []int) {
	return file_leaderboard_proto_rawDescGZIP(), []int{1}
}

func (x *LeaderboardEntry) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *LeaderboardEntry) GetProfile() *common.ProfileSummary {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *LeaderboardEntry) GetTrophies() int32 {
	if x != nil {
		return x.Trophies
	}
	return 0
}

type LeaderboardTopResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LeaderboardEntry    `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	SeasonId      int32                  `protobuf:"varint,2,opt,name=season_id,json=seasonId,proto3" json:"season_id,omitempty"` // 实际查到的赛季（确认与 req 一致）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardTopResp) Reset() {
	*x = LeaderboardTopResp{}
	mi := &file_leaderboard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardTopResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardTopResp) ProtoMessage() {}

func (x *LeaderboardTopResp) ProtoReflect() protoreflect.Message {
	mi := &file_leaderboard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardTopResp.ProtoReflect.Descriptor instead.
func (*LeaderboardTopResp) Descriptor() ([]byte, []int) {
	return file_leaderboard_proto_rawDescGZIP(), []int{2}
}

func (x *LeaderboardTopResp) GetEntries() []*LeaderboardEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *LeaderboardTopResp) GetSeasonId() int32 {
	if x != nil {
		return x.SeasonId
	}
	return 0
}

var File_leaderboard_proto protoreflect.FileDescriptor

const file_leaderboard_proto_rawDesc = "" +
	"\n" +
	"\x11leaderboard.proto\x12\agame.v4\x1a\fcommon.proto\"\xb4\x01\n" +
	"\x11LeaderboardTopReq\x126\n" +
	"\x05scope\x18\x01 \x01(\x0e2 .game.v4.LeaderboardTopReq.ScopeR\x05scope\x12\x1b\n" +
	"\tseason_id\x18\x02 \x01(\x05R\bseasonId\x12\x14\n" +
	"\x05arena\x18\x03 \x01(\x05R\x05arena\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\x1e\n" +
	"\x05Scope\x12\n" +
	"\n" +
	"\x06GLOBAL\x10\x00\x12\t\n" +
	"\x05ARENA\x10\x01\"u\n" +
	"\x10LeaderboardEntry\x12\x12\n" +
	"\x04rank\x18\x01 \x01(\x05R\x04rank\x121\n" +
	"\aprofile\x18\x02 \x01(\v2\x17.game.v4.ProfileSummaryR\aprofile\x12\x1a\n" +
	"\btrophies\x18\x03 \x01(\x05R\btrophies\"f\n" +
	"\x12LeaderboardTopResp\x123\n" +
	"\aentries\x18\x01 \x03(\v2\x19.game.v4.LeaderboardEntryR\aentries\x12\x1b\n" +
	"\tseason_id\x18\x02 \x01(\x05R\bseasonIdBFZDgithub.com/jchensh/godot-clash-pusher/server/internal/pb/leaderboardb\x06proto3"

var (
	file_leaderboard_proto_rawDescOnce sync.Once
	file_leaderboard_proto_rawDescData []byte
)

func file_leaderboard_proto_rawDescGZIP() []byte {
	file_leaderboard_proto_rawDescOnce.Do(func() {
		file_leaderboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_leaderboard_proto_rawDesc), len(file_leaderboard_proto_rawDesc)))
	})
	return file_leaderboard_proto_rawDescData
}

var file_leaderboard_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_leaderboard_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_leaderboard_proto_goTypes = []any{
	(LeaderboardTopReq_Scope)(0),  // 0: game.v4.LeaderboardTopReq.Scope
	(*LeaderboardTopReq)(nil),     // 1: game.v4.LeaderboardTopReq
	(*LeaderboardEntry)(nil),      // 2: game.v4.LeaderboardEntry
	(*LeaderboardTopResp)(nil),    // 3: game.v4.LeaderboardTopResp
	(*common.ProfileSummary)(nil), // 4: game.v4.ProfileSummary
}
var file_leaderboard_proto_depIdxs = []int32{
	0, // 0: game.v4.LeaderboardTopReq.scope:type_name -> game.v4.LeaderboardTopReq.Scope
	4, // 1: game.v4.LeaderboardEntry.profile:type_name -> game.v4.ProfileSummary
	2, // 2: game.v4.LeaderboardTopResp.entries:type_name -> game.v4.LeaderboardEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_leaderboard_proto_init() }
func file_leaderboard_proto_init() {
	if File_leaderboard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_leaderboard_proto_rawDesc), len(file_leaderboard_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_leaderboard_proto_goTypes,
		DependencyIndexes: file_leaderboard_proto_depIdxs,
		EnumInfos:         file_leaderboard_proto_enumTypes,
		MessageInfos:      file_leaderboard_proto_msgTypes,
	}.Build()
	File_leaderboard_proto = out.File
	file_leaderboard_proto_goTypes = nil
	file_leaderboard_proto_depIdxs = nil
}
