// economy.proto — V5-N3/N4/N5/N6（决策 48）：服务器权威经济状态 + 结算动作。
//
// HTTP（api:8080，Bearer 会话令牌）：
//   GET  /v5/economy/state          → EconomyState
//   POST /v5/economy/upgrade        EconomyActionReq{card_id} → EconomyState（升级）
//   POST /v5/economy/rank-up        EconomyActionReq{card_id} → EconomyState（升阶）
//   POST /v5/economy/unlock         EconomyActionReq{card_id} → EconomyState（解锁）
//   POST /v5/economy/stage-clear    StageClearReq{stage_id,stars} → EconomyState（N5 通关发奖）
//   POST /v5/economy/collect-idle   CollectIdleReq{} → EconomyState（N6 挂机领取，now 全服务器定）
// 成本/上限/解锁门槛/进度连续/星数上限/挂机时钟全在服务器用服务器侧配置 + 服务器时间算（改本地无效）。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: economy.proto

package economy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CardState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	Level         int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	Rank          int32                  `protobuf:"varint,3,opt,name=rank,proto3" json:"rank,omitempty"`
	Shards        int32                  `protobuf:"varint,4,opt,name=shards,proto3" json:"shards,omitempty"`
	Unlocked      bool                   `protobuf:"varint,5,opt,name=unlocked,proto3" json:"unlocked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardState) Reset() {
	*x = CardState{}
	mi := &file_economy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardState) ProtoMessage() {}

func (x *CardState) ProtoReflect() protoreflect.Message {
	mi := &file_economy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardState.ProtoReflect.Descriptor instead.
func (*CardState) Descriptor() ([]byte, []int) {
	return file_economy_proto_rawDescGZIP(), []int{0}
}

func (x *CardState) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *CardState) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CardState) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *CardState) GetShards() int32 {
	if x != nil {
		return x.Shards
	}
	return 0
}

func (x *CardState) GetUnlocked() bool {
	if x != nil {
		return x.Unlocked
	}
	return false
}

type StageState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StageId       string                 `protobuf:"bytes,1,opt,name=stage_id,json=stageId,proto3" json:"stage_id,omitempty"`
	Stars         int32                  `protobuf:"varint,2,opt,name=stars,proto3" json:"stars,omitempty"`
	Cleared       bool                   `protobuf:"varint,3,opt,name=cleared,proto3" json:"cleared,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StageState) Reset() {
	*x = StageState{}
	mi := &file_economy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StageState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageState) ProtoMessage() {}

func (x *StageState) ProtoReflect() protoreflect.Message {
	mi := &file_economy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StageState.ProtoReflect.Descriptor instead.
func (*StageState) Descriptor() ([]byte, []int) {
	return file_economy_proto_rawDescGZIP(), []int{1}
}

func (x *StageState) GetStageId() string {
	if x != nil {
		return x.StageId
	}
	return ""
}

func (x *StageState) GetStars() int32 {
	if x != nil {
		return x.Stars
	}
	return 0
}

func (x *StageState) GetCleared() bool {
	if x != nil {
		return x.Cleared
	}
	return false
}

type EconomyState struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Gold              int64                  `protobuf:"varint,1,opt,name=gold,proto3" json:"gold,omitempty"`
	Gems              int64                  `protobuf:"varint,2,opt,name=gems,proto3" json:"gems,omitempty"`
	IdleLastCollectTs int64                  `protobuf:"varint,3,opt,name=idle_last_collect_ts,json=idleLastCollectTs,proto3" json:"idle_last_collect_ts,omitempty"`
	HighestCleared    string                 `protobuf:"bytes,4,opt,name=highest_cleared,json=highestCleared,proto3" json:"highest_cleared,omitempty"`
	Cards             []*CardState           `protobuf:"bytes,5,rep,name=cards,proto3" json:"cards,omitempty"`
	Stages            []*StageState          `protobuf:"bytes,6,rep,name=stages,proto3" json:"stages,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EconomyState) Reset() {
	*x = EconomyState{}
	mi := &file_economy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EconomyState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EconomyState) ProtoMessage() {}

func (x *EconomyState) ProtoReflect() protoreflect.Message {
	mi := &file_economy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EconomyState.ProtoReflect.Descriptor instead.
func (*EconomyState) Descriptor() ([]byte, []int) {
	return file_economy_proto_rawDescGZIP(), []int{2}
}

func (x *EconomyState) GetGold() int64 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *EconomyState) GetGems() int64 {
	if x != nil {
		return x.Gems
	}
	return 0
}

func (x *EconomyState) GetIdleLastCollectTs() int64 {
	if x != nil {
		return x.IdleLastCollectTs
	}
	return 0
}

func (x *EconomyState) GetHighestCleared() string {
	if x != nil {
		return x.HighestCleared
	}
	return ""
}

func (x *EconomyState) GetCards() []*CardState {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *EconomyState) GetStages() []*StageState {
	if x != nil {
		return x.Stages
	}
	return nil
}

// upgrade / rank_up / unlock 共用（按 HTTP 路径区分动作）。
type EconomyActionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EconomyActionReq) Reset() {
	*x = EconomyActionReq{}
	mi := &file_economy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EconomyActionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EconomyActionReq) ProtoMessage() {}

func (x *EconomyActionReq) ProtoReflect() protoreflect.Message {
	mi := &file_economy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EconomyActionReq.ProtoReflect.Descriptor instead.
func (*EconomyActionReq) Descriptor() ([]byte, []int) {
	return file_economy_proto_rawDescGZIP(), []int{3}
}

func (x *EconomyActionReq) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

// N5 通关上报：客户端把 (stage_id, stars) 报上来，服务器 sanity 校验（关卡存在/
// stars≥1/stars≤配置上限/进度连续防跳关）+ 发首通/重复奖励 + 记进度，回新 EconomyState。
type StageClearReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StageId       string                 `protobuf:"bytes,1,opt,name=stage_id,json=stageId,proto3" json:"stage_id,omitempty"`
	Stars         int32                  `protobuf:"varint,2,opt,name=stars,proto3" json:"stars,omitempty"` // 0=未取胜（拒）；≥1=通关星数（不能超该关 stars 配置条数）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StageClearReq) Reset() {
	*x = StageClearReq{}
	mi := &file_economy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StageClearReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageClearReq) ProtoMessage() {}

func (x *StageClearReq) ProtoReflect() protoreflect.Message {
	mi := &file_economy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StageClearReq.ProtoReflect.Descriptor instead.
func (*StageClearReq) Descriptor() ([]byte, []int) {
	return file_economy_proto_rawDescGZIP(), []int{4}
}

func (x *StageClearReq) GetStageId() string {
	if x != nil {
		return x.StageId
	}
	return ""
}

func (x *StageClearReq) GetStars() int32 {
	if x != nil {
		return x.Stars
	}
	return 0
}

// N6 挂机领取：无参（now 全服务器定，改本地时钟无效）。服务器按 (now − last_collect)
// 算累计金币（rate × min(elapsed/cap_hours)，章节驱动）→ 发到 gold + last_collect=now。
type CollectIdleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectIdleReq) Reset() {
	*x = CollectIdleReq{}
	mi := &file_economy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectIdleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectIdleReq) ProtoMessage() {}

func (x *CollectIdleReq) ProtoReflect() protoreflect.Message {
	mi := &file_economy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectIdleReq.ProtoReflect.Descriptor instead.
func (*CollectIdleReq) Descriptor() ([]byte, []int) {
	return file_economy_proto_rawDescGZIP(), []int{5}
}

var File_economy_proto protoreflect.FileDescriptor

const file_economy_proto_rawDesc = "" +
	"\n" +
	"\reconomy.proto\x12\agame.v4\"\x82\x01\n" +
	"\tCardState\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\x12\x12\n" +
	"\x04rank\x18\x03 \x01(\x05R\x04rank\x12\x16\n" +
	"\x06shards\x18\x04 \x01(\x05R\x06shards\x12\x1a\n" +
	"\bunlocked\x18\x05 \x01(\bR\bunlocked\"W\n" +
	"\n" +
	"StageState\x12\x19\n" +
	"\bstage_id\x18\x01 \x01(\tR\astageId\x12\x14\n" +
	"\x05stars\x18\x02 \x01(\x05R\x05stars\x12\x18\n" +
	"\acleared\x18\x03 \x01(\bR\acleared\"\xe7\x01\n" +
	"\fEconomyState\x12\x12\n" +
	"\x04gold\x18\x01 \x01(\x03R\x04gold\x12\x12\n" +
	"\x04gems\x18\x02 \x01(\x03R\x04gems\x12/\n" +
	"\x14idle_last_collect_ts\x18\x03 \x01(\x03R\x11idleLastCollectTs\x12'\n" +
	"\x0fhighest_cleared\x18\x04 \x01(\tR\x0ehighestCleared\x12(\n" +
	"\x05cards\x18\x05 \x03(\v2\x12.game.v4.CardStateR\x05cards\x12+\n" +
	"\x06stages\x18\x06 \x03(\v2\x13.game.v4.StageStateR\x06stages\"+\n" +
	"\x10EconomyActionReq\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\"@\n" +
	"\rStageClearReq\x12\x19\n" +
	"\bstage_id\x18\x01 \x01(\tR\astageId\x12\x14\n" +
	"\x05stars\x18\x02 \x01(\x05R\x05stars\"\x10\n" +
	"\x0eCollectIdleReqBBZ@github.com/jchensh/godot-clash-pusher/server/internal/pb/economyb\x06proto3"

var (
	file_economy_proto_rawDescOnce sync.Once
	file_economy_proto_rawDescData []byte
)

func file_economy_proto_rawDescGZIP() []byte {
	file_economy_proto_rawDescOnce.Do(func() {
		file_economy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_economy_proto_rawDesc), len(file_economy_proto_rawDesc)))
	})
	return file_economy_proto_rawDescData
}

var file_economy_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_economy_proto_goTypes = []any{
	(*CardState)(nil),        // 0: game.v4.CardState
	(*StageState)(nil),       // 1: game.v4.StageState
	(*EconomyState)(nil),     // 2: game.v4.EconomyState
	(*EconomyActionReq)(nil), // 3: game.v4.EconomyActionReq
	(*StageClearReq)(nil),    // 4: game.v4.StageClearReq
	(*CollectIdleReq)(nil),   // 5: game.v4.CollectIdleReq
}
var file_economy_proto_depIdxs = []int32{
	0, // 0: game.v4.EconomyState.cards:type_name -> game.v4.CardState
	1, // 1: game.v4.EconomyState.stages:type_name -> game.v4.StageState
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_economy_proto_init() }
func file_economy_proto_init() {
	if File_economy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_economy_proto_rawDesc), len(file_economy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_economy_proto_goTypes,
		DependencyIndexes: file_economy_proto_depIdxs,
		MessageInfos:      file_economy_proto_msgTypes,
	}.Build()
	File_economy_proto = out.File
	file_economy_proto_goTypes = nil
	file_economy_proto_depIdxs = nil
}
