// economy.proto — V5-N3/N4/N5/N6（决策 48）：服务器权威经济状态 + 结算动作。
//
// HTTP（api:8080，Bearer 会话令牌）：
//   GET  /v5/economy/state          → EconomyState
//   POST /v5/economy/upgrade        EconomyActionReq{card_id} → EconomyState（升级）
//   POST /v5/economy/rank-up        EconomyActionReq{card_id} → EconomyState（升阶）
//   POST /v5/economy/unlock         EconomyActionReq{card_id} → EconomyState（解锁）
//   POST /v5/economy/stage-clear    StageClearReq{stage_id,stars} → EconomyState（N5 通关发奖）
//   POST /v5/economy/collect-idle   CollectIdleReq{} → EconomyState（N6 挂机领取，now 全服务器定）
// 成本/上限/解锁门槛/进度连续/星数上限/挂机时钟全在服务器用服务器侧配置 + 服务器时间算（改本地无效）。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: economy.proto

package economy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CardState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	Level         int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	Rank          int32                  `protobuf:"varint,3,opt,name=rank,proto3" json:"rank,omitempty"`
	Shards        int32                  `protobuf:"varint,4,opt,name=shards,proto3" json:"shards,omitempty"`
	Unlocked      bool                   `protobuf:"varint,5,opt,name=unlocked,proto3" json:"unlocked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardState) Reset() {
	*x = CardState{}
	mi := &file_economy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardState) ProtoMessage() {}

func (x *CardState) ProtoReflect() protoreflect.Message {
	mi := &file_economy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardState.ProtoReflect.Descriptor instead.
func (*CardState) Descriptor() ([]byte, []int) {
	return file_economy_proto_rawDescGZIP(), []int{0}
}

func (x *CardState) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *CardState) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CardState) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *CardState) GetShards() int32 {
	if x != nil {
		return x.Shards
	}
	return 0
}

func (x *CardState) GetUnlocked() bool {
	if x != nil {
		return x.Unlocked
	}
	return false
}

type StageState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StageId       string                 `protobuf:"bytes,1,opt,name=stage_id,json=stageId,proto3" json:"stage_id,omitempty"`
	Stars         int32                  `protobuf:"varint,2,opt,name=stars,proto3" json:"stars,omitempty"`
	Cleared       bool                   `protobuf:"varint,3,opt,name=cleared,proto3" json:"cleared,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StageState) Reset() {
	*x = StageState{}
	mi := &file_economy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StageState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageState) ProtoMessage() {}

func (x *StageState) ProtoReflect() protoreflect.Message {
	mi := &file_economy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StageState.ProtoReflect.Descriptor instead.
func (*StageState) Descriptor() ([]byte, []int) {
	return file_economy_proto_rawDescGZIP(), []int{1}
}

func (x *StageState) GetStageId() string {
	if x != nil {
		return x.StageId
	}
	return ""
}

func (x *StageState) GetStars() int32 {
	if x != nil {
		return x.Stars
	}
	return 0
}

func (x *StageState) GetCleared() bool {
	if x != nil {
		return x.Cleared
	}
	return false
}

type EconomyState struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Gold              int64                  `protobuf:"varint,1,opt,name=gold,proto3" json:"gold,omitempty"`
	Gems              int64                  `protobuf:"varint,2,opt,name=gems,proto3" json:"gems,omitempty"`
	IdleLastCollectTs int64                  `protobuf:"varint,3,opt,name=idle_last_collect_ts,json=idleLastCollectTs,proto3" json:"idle_last_collect_ts,omitempty"`
	HighestCleared    string                 `protobuf:"bytes,4,opt,name=highest_cleared,json=highestCleared,proto3" json:"highest_cleared,omitempty"`
	Cards             []*CardState           `protobuf:"bytes,5,rep,name=cards,proto3" json:"cards,omitempty"`
	Stages            []*StageState          `protobuf:"bytes,6,rep,name=stages,proto3" json:"stages,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EconomyState) Reset() {
	*x = EconomyState{}
	mi := &file_economy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EconomyState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EconomyState) ProtoMessage() {}

func (x *EconomyState) ProtoReflect() protoreflect.Message {
	mi := &file_economy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EconomyState.ProtoReflect.Descriptor instead.
func (*EconomyState) Descriptor() ([]byte, []int) {
	return file_economy_proto_rawDescGZIP(), []int{2}
}

func (x *EconomyState) GetGold() int64 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *EconomyState) GetGems() int64 {
	if x != nil {
		return x.Gems
	}
	return 0
}

func (x *EconomyState) GetIdleLastCollectTs() int64 {
	if x != nil {
		return x.IdleLastCollectTs
	}
	return 0
}

func (x *EconomyState) GetHighestCleared() string {
	if x != nil {
		return x.HighestCleared
	}
	return ""
}

func (x *EconomyState) GetCards() []*CardState {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *EconomyState) GetStages() []*StageState {
	if x != nil {
		return x.Stages
	}
	return nil
}

// upgrade / rank_up / unlock 共用（按 HTTP 路径区分动作）。
type EconomyActionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EconomyActionReq) Reset() {
	*x = EconomyActionReq{}
	mi := &file_economy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EconomyActionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EconomyActionReq) ProtoMessage() {}

func (x *EconomyActionReq) ProtoReflect() protoreflect.Message {
	mi := &file_economy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EconomyActionReq.ProtoReflect.Descriptor instead.
func (*EconomyActionReq) Descriptor() ([]byte, []int) {
	return file_economy_proto_rawDescGZIP(), []int{3}
}

func (x *EconomyActionReq) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

// N5 通关上报：客户端把 (stage_id, stars) 报上来，服务器 sanity 校验（关卡存在/
// stars≥1/stars≤配置上限/进度连续防跳关）+ 发首通/重复奖励 + 记进度，回新 EconomyState。
// KAN-78 防作弊扩展：必须带本局 battle_id（PveStartResp 发的）+ 战报摘要；服务器校验
// battle 属己/关匹配/未消费（防重放）、墙钟时长 ≥ 下限、声称 tick 与墙钟一致（无法时间
// 压缩）、星数与摘要自洽（king_hp/time_under）。
type StageClearReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StageId       string                 `protobuf:"bytes,1,opt,name=stage_id,json=stageId,proto3" json:"stage_id,omitempty"`
	Stars         int32                  `protobuf:"varint,2,opt,name=stars,proto3" json:"stars,omitempty"`                       // 0=未取胜（拒）；≥1=通关星数（不能超该关 stars 配置条数）
	BattleId      int64                  `protobuf:"varint,3,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"` // KAN-78：本局 PVE 战斗会话 id（PveStart 下发）
	Summary       *BattleSummary         `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`                    // KAN-78：战报摘要（与 stars 声明交叉校验）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StageClearReq) Reset() {
	*x = StageClearReq{}
	mi := &file_economy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StageClearReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageClearReq) ProtoMessage() {}

func (x *StageClearReq) ProtoReflect() protoreflect.Message {
	mi := &file_economy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StageClearReq.ProtoReflect.Descriptor instead.
func (*StageClearReq) Descriptor() ([]byte, []int) {
	return file_economy_proto_rawDescGZIP(), []int{4}
}

func (x *StageClearReq) GetStageId() string {
	if x != nil {
		return x.StageId
	}
	return ""
}

func (x *StageClearReq) GetStars() int32 {
	if x != nil {
		return x.Stars
	}
	return 0
}

func (x *StageClearReq) GetBattleId() int64 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

func (x *StageClearReq) GetSummary() *BattleSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

type PveStartReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StageId       string                 `protobuf:"bytes,1,opt,name=stage_id,json=stageId,proto3" json:"stage_id,omitempty"`
	Deck          []string               `protobuf:"bytes,2,rep,name=deck,proto3" json:"deck,omitempty"` // 本局 8 张卡组（服务器校验全 unlocked，堵未解锁卡进战斗）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PveStartReq) Reset() {
	*x = PveStartReq{}
	mi := &file_economy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PveStartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PveStartReq) ProtoMessage() {}

func (x *PveStartReq) ProtoReflect() protoreflect.Message {
	mi := &file_economy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PveStartReq.ProtoReflect.Descriptor instead.
func (*PveStartReq) Descriptor() ([]byte, []int) {
	return file_economy_proto_rawDescGZIP(), []int{5}
}

func (x *PveStartReq) GetStageId() string {
	if x != nil {
		return x.StageId
	}
	return ""
}

func (x *PveStartReq) GetDeck() []string {
	if x != nil {
		return x.Deck
	}
	return nil
}

type PveStartResp struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	BattleId int64                  `protobuf:"varint,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	// K4（DESIGN_KINGDOM）：王国城防 → 我方三塔加成（整数百分比，服务器权威定值下发；
	// 同值写进 pve_battles.progress 的 "_towers" 保留键 → 重放验证器逐 bit 复现）。
	TowerHpPct    int32 `protobuf:"varint,2,opt,name=tower_hp_pct,json=towerHpPct,proto3" json:"tower_hp_pct,omitempty"`
	TowerDmgPct   int32 `protobuf:"varint,3,opt,name=tower_dmg_pct,json=towerDmgPct,proto3" json:"tower_dmg_pct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PveStartResp) Reset() {
	*x = PveStartResp{}
	mi := &file_economy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PveStartResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PveStartResp) ProtoMessage() {}

func (x *PveStartResp) ProtoReflect() protoreflect.Message {
	mi := &file_economy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PveStartResp.ProtoReflect.Descriptor instead.
func (*PveStartResp) Descriptor() ([]byte, []int) {
	return file_economy_proto_rawDescGZIP(), []int{6}
}

func (x *PveStartResp) GetBattleId() int64 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

func (x *PveStartResp) GetTowerHpPct() int32 {
	if x != nil {
		return x.TowerHpPct
	}
	return 0
}

func (x *PveStartResp) GetTowerDmgPct() int32 {
	if x != nil {
		return x.TowerDmgPct
	}
	return 0
}

// 一条出牌指令（双方都录：玩家在 tick 间隙出牌 phase=0，AI 在 tick 内出牌 phase=1；
// 相位区分让服务端重放器能逐 bit 复现原局时序——见 logic/pve_replay.gd）。
type PveCmd struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Tick  int32                  `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"` // gap 牌=出牌时已完成的 tick 数 N（重放在第 N+1 tick regen 前应用）；
	// in 牌=所在 tick 序号（重放在该 tick regen 后应用）
	Phase         int32  `protobuf:"varint,2,opt,name=phase,proto3" json:"phase,omitempty"` // 0=gap（tick 间隙，玩家）/ 1=in（tick 内，AI）
	Side          int32  `protobuf:"varint,3,opt,name=side,proto3" json:"side,omitempty"`   // 1=player / 2=opponent(AI)
	CardId        string `protobuf:"bytes,4,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	XMilli        int32  `protobuf:"varint,5,opt,name=x_milli,json=xMilli,proto3" json:"x_milli,omitempty"` // tile × 1000（与 battle.proto DeployCmd 同款量化）
	YMilli        int32  `protobuf:"varint,6,opt,name=y_milli,json=yMilli,proto3" json:"y_milli,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PveCmd) Reset() {
	*x = PveCmd{}
	mi := &file_economy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PveCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PveCmd) ProtoMessage() {}

func (x *PveCmd) ProtoReflect() protoreflect.Message {
	mi := &file_economy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PveCmd.ProtoReflect.Descriptor instead.
func (*PveCmd) Descriptor() ([]byte, []int) {
	return file_economy_proto_rawDescGZIP(), []int{7}
}

func (x *PveCmd) GetTick() int32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *PveCmd) GetPhase() int32 {
	if x != nil {
		return x.Phase
	}
	return 0
}

func (x *PveCmd) GetSide() int32 {
	if x != nil {
		return x.Side
	}
	return 0
}

func (x *PveCmd) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *PveCmd) GetXMilli() int32 {
	if x != nil {
		return x.XMilli
	}
	return 0
}

func (x *PveCmd) GetYMilli() int32 {
	if x != nil {
		return x.YMilli
	}
	return 0
}

// 周期状态哈希（每 10 tick 一条，Match.state_hash()）。改内存改状态 → hash 与重放不符。
type PveHashRec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tick          int32                  `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	Hash          []byte                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"` // sha256, 32 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PveHashRec) Reset() {
	*x = PveHashRec{}
	mi := &file_economy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PveHashRec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PveHashRec) ProtoMessage() {}

func (x *PveHashRec) ProtoReflect() protoreflect.Message {
	mi := &file_economy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PveHashRec.ProtoReflect.Descriptor instead.
func (*PveHashRec) Descriptor() ([]byte, []int) {
	return file_economy_proto_rawDescGZIP(), []int{8}
}

func (x *PveHashRec) GetTick() int32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *PveHashRec) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type PveReportReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BattleId      int64                  `protobuf:"varint,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	Cmds          []*PveCmd              `protobuf:"bytes,2,rep,name=cmds,proto3" json:"cmds,omitempty"`     // 自上一批以来新增的指令（追加式）
	Hashes        []*PveHashRec          `protobuf:"bytes,3,rep,name=hashes,proto3" json:"hashes,omitempty"` // 自上一批以来新增的哈希
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PveReportReq) Reset() {
	*x = PveReportReq{}
	mi := &file_economy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PveReportReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PveReportReq) ProtoMessage() {}

func (x *PveReportReq) ProtoReflect() protoreflect.Message {
	mi := &file_economy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PveReportReq.ProtoReflect.Descriptor instead.
func (*PveReportReq) Descriptor() ([]byte, []int) {
	return file_economy_proto_rawDescGZIP(), []int{9}
}

func (x *PveReportReq) GetBattleId() int64 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

func (x *PveReportReq) GetCmds() []*PveCmd {
	if x != nil {
		return x.Cmds
	}
	return nil
}

func (x *PveReportReq) GetHashes() []*PveHashRec {
	if x != nil {
		return x.Hashes
	}
	return nil
}

type PveReportResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PveReportResp) Reset() {
	*x = PveReportResp{}
	mi := &file_economy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PveReportResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PveReportResp) ProtoMessage() {}

func (x *PveReportResp) ProtoReflect() protoreflect.Message {
	mi := &file_economy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PveReportResp.ProtoReflect.Descriptor instead.
func (*PveReportResp) Descriptor() ([]byte, []int) {
	return file_economy_proto_rawDescGZIP(), []int{10}
}

func (x *PveReportResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// 战报摘要（StageClear 附带，层1 sanity；重放器复算值与之交叉验证）。
type BattleSummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DurationTicks  int32                  `protobuf:"varint,1,opt,name=duration_ticks,json=durationTicks,proto3" json:"duration_ticks,omitempty"`      // 本局逻辑 tick 总数（10Hz）
	DeployCount    int32                  `protobuf:"varint,2,opt,name=deploy_count,json=deployCount,proto3" json:"deploy_count,omitempty"`            // 玩家出牌次数
	KingHpPermille int32                  `protobuf:"varint,3,opt,name=king_hp_permille,json=kingHpPermille,proto3" json:"king_hp_permille,omitempty"` // 我方王塔血量千分比 0~1000（判 king_hp_pct 星用）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BattleSummary) Reset() {
	*x = BattleSummary{}
	mi := &file_economy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleSummary) ProtoMessage() {}

func (x *BattleSummary) ProtoReflect() protoreflect.Message {
	mi := &file_economy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleSummary.ProtoReflect.Descriptor instead.
func (*BattleSummary) Descriptor() ([]byte, []int) {
	return file_economy_proto_rawDescGZIP(), []int{11}
}

func (x *BattleSummary) GetDurationTicks() int32 {
	if x != nil {
		return x.DurationTicks
	}
	return 0
}

func (x *BattleSummary) GetDeployCount() int32 {
	if x != nil {
		return x.DeployCount
	}
	return 0
}

func (x *BattleSummary) GetKingHpPermille() int32 {
	if x != nil {
		return x.KingHpPermille
	}
	return 0
}

// N6 挂机领取：无参（now 全服务器定，改本地时钟无效）。服务器按 (now − last_collect)
// 算累计金币（rate × min(elapsed/cap_hours)，章节驱动）→ 发到 gold + last_collect=now。
type CollectIdleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectIdleReq) Reset() {
	*x = CollectIdleReq{}
	mi := &file_economy_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectIdleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectIdleReq) ProtoMessage() {}

func (x *CollectIdleReq) ProtoReflect() protoreflect.Message {
	mi := &file_economy_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectIdleReq.ProtoReflect.Descriptor instead.
func (*CollectIdleReq) Descriptor() ([]byte, []int) {
	return file_economy_proto_rawDescGZIP(), []int{12}
}

var File_economy_proto protoreflect.FileDescriptor

const file_economy_proto_rawDesc = "" +
	"\n" +
	"\reconomy.proto\x12\agame.v4\"\x82\x01\n" +
	"\tCardState\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\x12\x12\n" +
	"\x04rank\x18\x03 \x01(\x05R\x04rank\x12\x16\n" +
	"\x06shards\x18\x04 \x01(\x05R\x06shards\x12\x1a\n" +
	"\bunlocked\x18\x05 \x01(\bR\bunlocked\"W\n" +
	"\n" +
	"StageState\x12\x19\n" +
	"\bstage_id\x18\x01 \x01(\tR\astageId\x12\x14\n" +
	"\x05stars\x18\x02 \x01(\x05R\x05stars\x12\x18\n" +
	"\acleared\x18\x03 \x01(\bR\acleared\"\xe7\x01\n" +
	"\fEconomyState\x12\x12\n" +
	"\x04gold\x18\x01 \x01(\x03R\x04gold\x12\x12\n" +
	"\x04gems\x18\x02 \x01(\x03R\x04gems\x12/\n" +
	"\x14idle_last_collect_ts\x18\x03 \x01(\x03R\x11idleLastCollectTs\x12'\n" +
	"\x0fhighest_cleared\x18\x04 \x01(\tR\x0ehighestCleared\x12(\n" +
	"\x05cards\x18\x05 \x03(\v2\x12.game.v4.CardStateR\x05cards\x12+\n" +
	"\x06stages\x18\x06 \x03(\v2\x13.game.v4.StageStateR\x06stages\"+\n" +
	"\x10EconomyActionReq\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\"\x8f\x01\n" +
	"\rStageClearReq\x12\x19\n" +
	"\bstage_id\x18\x01 \x01(\tR\astageId\x12\x14\n" +
	"\x05stars\x18\x02 \x01(\x05R\x05stars\x12\x1b\n" +
	"\tbattle_id\x18\x03 \x01(\x03R\bbattleId\x120\n" +
	"\asummary\x18\x04 \x01(\v2\x16.game.v4.BattleSummaryR\asummary\"<\n" +
	"\vPveStartReq\x12\x19\n" +
	"\bstage_id\x18\x01 \x01(\tR\astageId\x12\x12\n" +
	"\x04deck\x18\x02 \x03(\tR\x04deck\"q\n" +
	"\fPveStartResp\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\x03R\bbattleId\x12 \n" +
	"\ftower_hp_pct\x18\x02 \x01(\x05R\n" +
	"towerHpPct\x12\"\n" +
	"\rtower_dmg_pct\x18\x03 \x01(\x05R\vtowerDmgPct\"\x91\x01\n" +
	"\x06PveCmd\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\x05R\x04tick\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\x05R\x05phase\x12\x12\n" +
	"\x04side\x18\x03 \x01(\x05R\x04side\x12\x17\n" +
	"\acard_id\x18\x04 \x01(\tR\x06cardId\x12\x17\n" +
	"\ax_milli\x18\x05 \x01(\x05R\x06xMilli\x12\x17\n" +
	"\ay_milli\x18\x06 \x01(\x05R\x06yMilli\"4\n" +
	"\n" +
	"PveHashRec\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\x05R\x04tick\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\fR\x04hash\"}\n" +
	"\fPveReportReq\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\x03R\bbattleId\x12#\n" +
	"\x04cmds\x18\x02 \x03(\v2\x0f.game.v4.PveCmdR\x04cmds\x12+\n" +
	"\x06hashes\x18\x03 \x03(\v2\x13.game.v4.PveHashRecR\x06hashes\"\x1f\n" +
	"\rPveReportResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\x83\x01\n" +
	"\rBattleSummary\x12%\n" +
	"\x0eduration_ticks\x18\x01 \x01(\x05R\rdurationTicks\x12!\n" +
	"\fdeploy_count\x18\x02 \x01(\x05R\vdeployCount\x12(\n" +
	"\x10king_hp_permille\x18\x03 \x01(\x05R\x0ekingHpPermille\"\x10\n" +
	"\x0eCollectIdleReqBBZ@github.com/jchensh/godot-clash-pusher/server/internal/pb/economyb\x06proto3"

var (
	file_economy_proto_rawDescOnce sync.Once
	file_economy_proto_rawDescData []byte
)

func file_economy_proto_rawDescGZIP() []byte {
	file_economy_proto_rawDescOnce.Do(func() {
		file_economy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_economy_proto_rawDesc), len(file_economy_proto_rawDesc)))
	})
	return file_economy_proto_rawDescData
}

var file_economy_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_economy_proto_goTypes = []any{
	(*CardState)(nil),        // 0: game.v4.CardState
	(*StageState)(nil),       // 1: game.v4.StageState
	(*EconomyState)(nil),     // 2: game.v4.EconomyState
	(*EconomyActionReq)(nil), // 3: game.v4.EconomyActionReq
	(*StageClearReq)(nil),    // 4: game.v4.StageClearReq
	(*PveStartReq)(nil),      // 5: game.v4.PveStartReq
	(*PveStartResp)(nil),     // 6: game.v4.PveStartResp
	(*PveCmd)(nil),           // 7: game.v4.PveCmd
	(*PveHashRec)(nil),       // 8: game.v4.PveHashRec
	(*PveReportReq)(nil),     // 9: game.v4.PveReportReq
	(*PveReportResp)(nil),    // 10: game.v4.PveReportResp
	(*BattleSummary)(nil),    // 11: game.v4.BattleSummary
	(*CollectIdleReq)(nil),   // 12: game.v4.CollectIdleReq
}
var file_economy_proto_depIdxs = []int32{
	0,  // 0: game.v4.EconomyState.cards:type_name -> game.v4.CardState
	1,  // 1: game.v4.EconomyState.stages:type_name -> game.v4.StageState
	11, // 2: game.v4.StageClearReq.summary:type_name -> game.v4.BattleSummary
	7,  // 3: game.v4.PveReportReq.cmds:type_name -> game.v4.PveCmd
	8,  // 4: game.v4.PveReportReq.hashes:type_name -> game.v4.PveHashRec
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_economy_proto_init() }
func file_economy_proto_init() {
	if File_economy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_economy_proto_rawDesc), len(file_economy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_economy_proto_goTypes,
		DependencyIndexes: file_economy_proto_depIdxs,
		MessageInfos:      file_economy_proto_msgTypes,
	}.Build()
	File_economy_proto = out.File
	file_economy_proto_goTypes = nil
	file_economy_proto_depIdxs = nil
}
