// battle.proto — 实时对战（lockstep）
//
// V4-S3（**头号工程**）：
//   1. 双方各发 JoinRoomReq（带自己的卡组）-> 服务端回 JoinRoomResp（含双方卡组/关卡/side/start_tick）
//   2. 客户端每出兵/法术 -> 发 DeployCmd（带 tick=current+2，留出 RTT 缓冲）
//   3. 服务端每 tick 汇总双方 DeployCmd -> 广播 TickBundle 给双方
//   4. 双方各自 logic/ 推进同一 tick -> 周期上报 StateHashUp -> 服务端两端对帐
//   5. 一方 sim 判定结束 -> 发 BattleEndReport -> 服务端核对 -> 广播 BattleResultPush
//
// 注：lockstep 服务端**不跑 sim**，故对局结束（王塔归零/超时）由两端各自 sim 判定后上报，
// 服务端核对一致后拍板。状态哈希两端对帐捕获不同步（完整仲裁见 PLAN_V4 §5.4，S3 先记录）。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: battle.proto

package battle

import (
	common "github.com/jchensh/godot-clash-pusher/server/internal/pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BattleResultPush_Winner int32

const (
	BattleResultPush_DRAW   BattleResultPush_Winner = 0
	BattleResultPush_SIDE_1 BattleResultPush_Winner = 1
	BattleResultPush_SIDE_2 BattleResultPush_Winner = 2
)

// Enum value maps for BattleResultPush_Winner.
var (
	BattleResultPush_Winner_name = map[int32]string{
		0: "DRAW",
		1: "SIDE_1",
		2: "SIDE_2",
	}
	BattleResultPush_Winner_value = map[string]int32{
		"DRAW":   0,
		"SIDE_1": 1,
		"SIDE_2": 2,
	}
)

func (x BattleResultPush_Winner) Enum() *BattleResultPush_Winner {
	p := new(BattleResultPush_Winner)
	*p = x
	return p
}

func (x BattleResultPush_Winner) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BattleResultPush_Winner) Descriptor() protoreflect.EnumDescriptor {
	return file_battle_proto_enumTypes[0].Descriptor()
}

func (BattleResultPush_Winner) Type() protoreflect.EnumType {
	return &file_battle_proto_enumTypes[0]
}

func (x BattleResultPush_Winner) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BattleResultPush_Winner.Descriptor instead.
func (BattleResultPush_Winner) EnumDescriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{7, 0}
}

type BattleResultPush_Reason int32

const (
	BattleResultPush_REASON_UNKNOWN  BattleResultPush_Reason = 0
	BattleResultPush_KING_DESTROYED  BattleResultPush_Reason = 1 // 一方王塔归零
	BattleResultPush_TIMEOUT         BattleResultPush_Reason = 2 // match_duration 到，按剩余塔血总和判
	BattleResultPush_SURRENDER       BattleResultPush_Reason = 3 // 一方主动认输
	BattleResultPush_DISCONNECT      BattleResultPush_Reason = 4 // 一方断线超时
	BattleResultPush_HASH_DIVERGENCE BattleResultPush_Reason = 5 // 状态哈希仲裁判负
)

// Enum value maps for BattleResultPush_Reason.
var (
	BattleResultPush_Reason_name = map[int32]string{
		0: "REASON_UNKNOWN",
		1: "KING_DESTROYED",
		2: "TIMEOUT",
		3: "SURRENDER",
		4: "DISCONNECT",
		5: "HASH_DIVERGENCE",
	}
	BattleResultPush_Reason_value = map[string]int32{
		"REASON_UNKNOWN":  0,
		"KING_DESTROYED":  1,
		"TIMEOUT":         2,
		"SURRENDER":       3,
		"DISCONNECT":      4,
		"HASH_DIVERGENCE": 5,
	}
)

func (x BattleResultPush_Reason) Enum() *BattleResultPush_Reason {
	p := new(BattleResultPush_Reason)
	*p = x
	return p
}

func (x BattleResultPush_Reason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BattleResultPush_Reason) Descriptor() protoreflect.EnumDescriptor {
	return file_battle_proto_enumTypes[1].Descriptor()
}

func (BattleResultPush_Reason) Type() protoreflect.EnumType {
	return &file_battle_proto_enumTypes[1]
}

func (x BattleResultPush_Reason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BattleResultPush_Reason.Descriptor instead.
func (BattleResultPush_Reason) EnumDescriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{7, 1}
}

type JoinRoomReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Deck          []string               `protobuf:"bytes,2,rep,name=deck,proto3" json:"deck,omitempty"` // 本方 8 张卡组（lockstep 要两端互知对方牌）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomReq) Reset() {
	*x = JoinRoomReq{}
	mi := &file_battle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomReq) ProtoMessage() {}

func (x *JoinRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomReq.ProtoReflect.Descriptor instead.
func (*JoinRoomReq) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{0}
}

func (x *JoinRoomReq) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *JoinRoomReq) GetDeck() []string {
	if x != nil {
		return x.Deck
	}
	return nil
}

// 一张卡在本局的养成态（KAN-76：服务器建房时从 economy_cards 读出、权威下发）。
// 只发 level/rank 原始值、不发算好的乘区：两端用同版本配置的 PlayerData/CardProgression
// 各自换算（等价、确定性），且 rank 顺带驱动升阶技能积木解锁。
// 本 message 仅在 battle.proto 内使用（无跨文件引用，避 godobuf 跨文件内联坑）。
type CardProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	Level         int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	Rank          int32                  `protobuf:"varint,3,opt,name=rank,proto3" json:"rank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardProgress) Reset() {
	*x = CardProgress{}
	mi := &file_battle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardProgress) ProtoMessage() {}

func (x *CardProgress) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardProgress.ProtoReflect.Descriptor instead.
func (*CardProgress) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{1}
}

func (x *CardProgress) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *CardProgress) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CardProgress) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

type JoinRoomResp struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Ok        bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Opponent  *common.ProfileSummary `protobuf:"bytes,2,opt,name=opponent,proto3" json:"opponent,omitempty"`
	YourSide  int32                  `protobuf:"varint,3,opt,name=your_side,json=yourSide,proto3" json:"your_side,omitempty"`    // 与 MatchFoundPush 一致：1 或 2
	StartTick int32                  `protobuf:"varint,4,opt,name=start_tick,json=startTick,proto3" json:"start_tick,omitempty"` // 双方都 join 后服务端拍板开局 tick（含倒数缓冲）
	Seed      uint64                 `protobuf:"varint,5,opt,name=seed,proto3" json:"seed,omitempty"`
	Side1Deck []string               `protobuf:"bytes,6,rep,name=side1_deck,json=side1Deck,proto3" json:"side1_deck,omitempty"` // side 1 的卡组（两端都收，建同一初始态）
	Side2Deck []string               `protobuf:"bytes,7,rep,name=side2_deck,json=side2Deck,proto3" json:"side2_deck,omitempty"` // side 2 的卡组
	LevelId   string                 `protobuf:"bytes,8,opt,name=level_id,json=levelId,proto3" json:"level_id,omitempty"`       // 天梯关卡配置 id（如 ladder_01），两端各自本地加载
	// KAN-76：双方卡组每张卡的养成（按 card_id 与 sideN_deck 对应，顺序无关；两端都收，
	// 对 side1/side2 对称注入 → 同一方在两端算出逐 bit 相同的数值）。空 = 白板局（向后兼容）。
	Side1Progress []*CardProgress `protobuf:"bytes,9,rep,name=side1_progress,json=side1Progress,proto3" json:"side1_progress,omitempty"`
	Side2Progress []*CardProgress `protobuf:"bytes,10,rep,name=side2_progress,json=side2Progress,proto3" json:"side2_progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomResp) Reset() {
	*x = JoinRoomResp{}
	mi := &file_battle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomResp) ProtoMessage() {}

func (x *JoinRoomResp) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomResp.ProtoReflect.Descriptor instead.
func (*JoinRoomResp) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{2}
}

func (x *JoinRoomResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *JoinRoomResp) GetOpponent() *common.ProfileSummary {
	if x != nil {
		return x.Opponent
	}
	return nil
}

func (x *JoinRoomResp) GetYourSide() int32 {
	if x != nil {
		return x.YourSide
	}
	return 0
}

func (x *JoinRoomResp) GetStartTick() int32 {
	if x != nil {
		return x.StartTick
	}
	return 0
}

func (x *JoinRoomResp) GetSeed() uint64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

func (x *JoinRoomResp) GetSide1Deck() []string {
	if x != nil {
		return x.Side1Deck
	}
	return nil
}

func (x *JoinRoomResp) GetSide2Deck() []string {
	if x != nil {
		return x.Side2Deck
	}
	return nil
}

func (x *JoinRoomResp) GetLevelId() string {
	if x != nil {
		return x.LevelId
	}
	return ""
}

func (x *JoinRoomResp) GetSide1Progress() []*CardProgress {
	if x != nil {
		return x.Side1Progress
	}
	return nil
}

func (x *JoinRoomResp) GetSide2Progress() []*CardProgress {
	if x != nil {
		return x.Side2Progress
	}
	return nil
}

// 客户端 -> 服务端：单条出兵/法术指令。
// 坐标用 tile 量纲 × 1000 编码（避开浮点跨设备差异），客户端发前 round。
// 例：tile (4.5, 17.0) -> x=4500, y=17000。
type DeployCmd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tick          int32                  `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"` // 客户端指定的执行 tick（current_tick + 2）
	CardId        string                 `protobuf:"bytes,2,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	XMilli        int32                  `protobuf:"varint,3,opt,name=x_milli,json=xMilli,proto3" json:"x_milli,omitempty"` // tile × 1000
	YMilli        int32                  `protobuf:"varint,4,opt,name=y_milli,json=yMilli,proto3" json:"y_milli,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployCmd) Reset() {
	*x = DeployCmd{}
	mi := &file_battle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployCmd) ProtoMessage() {}

func (x *DeployCmd) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployCmd.ProtoReflect.Descriptor instead.
func (*DeployCmd) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{3}
}

func (x *DeployCmd) GetTick() int32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *DeployCmd) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *DeployCmd) GetXMilli() int32 {
	if x != nil {
		return x.XMilli
	}
	return 0
}

func (x *DeployCmd) GetYMilli() int32 {
	if x != nil {
		return x.YMilli
	}
	return 0
}

// 服务端 -> 客户端：本 tick 双方所有 deploy 的打包广播。
// 双方收到同一 TickBundle 后 logic/ 推进相同 tick。
// 空 deploys 也照发（保证 tick 同步、断线检测）。
type TickBundle struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Tick          int32                    `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	Deploys       []*TickBundle_SideDeploy `protobuf:"bytes,2,rep,name=deploys,proto3" json:"deploys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TickBundle) Reset() {
	*x = TickBundle{}
	mi := &file_battle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TickBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickBundle) ProtoMessage() {}

func (x *TickBundle) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickBundle.ProtoReflect.Descriptor instead.
func (*TickBundle) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{4}
}

func (x *TickBundle) GetTick() int32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *TickBundle) GetDeploys() []*TickBundle_SideDeploy {
	if x != nil {
		return x.Deploys
	}
	return nil
}

// 客户端 -> 服务端：周期上报本地状态哈希（每 10 tick 一次）。
// 服务端比对双方上报，hash 不一致 -> 标记不同步（S3 先记录，仲裁见 PLAN_V4 §5.4）。
type StateHashUp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tick          int32                  `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	Hash          []byte                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"` // sha256(units_state + towers_state + elixir)，32 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateHashUp) Reset() {
	*x = StateHashUp{}
	mi := &file_battle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateHashUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateHashUp) ProtoMessage() {}

func (x *StateHashUp) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateHashUp.ProtoReflect.Descriptor instead.
func (*StateHashUp) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{5}
}

func (x *StateHashUp) GetTick() int32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *StateHashUp) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

// 客户端 -> 服务端：本地 sim 判定对局结束（王塔归零 / 超时）。
// 服务端无 sim，靠两端上报；核对一致（或一方上报另一方未异议）后拍板。
type BattleEndReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tick          int32                  `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`                                 // 结束发生的 tick
	Winner        int32                  `protobuf:"varint,2,opt,name=winner,proto3" json:"winner,omitempty"`                             // 0=DRAW / 1=SIDE_1 / 2=SIDE_2（对齐 BattleResultPush.Winner）
	Reason        int32                  `protobuf:"varint,3,opt,name=reason,proto3" json:"reason,omitempty"`                             // 对齐 BattleResultPush.Reason
	Side_1Score   int32                  `protobuf:"varint,4,opt,name=side_1_score,json=side1Score,proto3" json:"side_1_score,omitempty"` // 剩余塔血总和（超时判定/核对用）
	Side_2Score   int32                  `protobuf:"varint,5,opt,name=side_2_score,json=side2Score,proto3" json:"side_2_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleEndReport) Reset() {
	*x = BattleEndReport{}
	mi := &file_battle_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleEndReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleEndReport) ProtoMessage() {}

func (x *BattleEndReport) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleEndReport.ProtoReflect.Descriptor instead.
func (*BattleEndReport) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{6}
}

func (x *BattleEndReport) GetTick() int32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *BattleEndReport) GetWinner() int32 {
	if x != nil {
		return x.Winner
	}
	return 0
}

func (x *BattleEndReport) GetReason() int32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

func (x *BattleEndReport) GetSide_1Score() int32 {
	if x != nil {
		return x.Side_1Score
	}
	return 0
}

func (x *BattleEndReport) GetSide_2Score() int32 {
	if x != nil {
		return x.Side_2Score
	}
	return 0
}

// 服务端 -> 客户端：对局结果推送。
type BattleResultPush struct {
	state               protoimpl.MessageState  `protogen:"open.v1"`
	Winner              BattleResultPush_Winner `protobuf:"varint,1,opt,name=winner,proto3,enum=game.v4.BattleResultPush_Winner" json:"winner,omitempty"`
	Reason              BattleResultPush_Reason `protobuf:"varint,2,opt,name=reason,proto3,enum=game.v4.BattleResultPush_Reason" json:"reason,omitempty"`
	Side_1Score         int32                   `protobuf:"varint,3,opt,name=side_1_score,json=side1Score,proto3" json:"side_1_score,omitempty"` // 剩余塔血总和（超时用）
	Side_2Score         int32                   `protobuf:"varint,4,opt,name=side_2_score,json=side2Score,proto3" json:"side_2_score,omitempty"`
	TrophiesDeltaSide_1 int32                   `protobuf:"varint,5,opt,name=trophies_delta_side_1,json=trophiesDeltaSide1,proto3" json:"trophies_delta_side_1,omitempty"` // ELO/段位变化
	TrophiesDeltaSide_2 int32                   `protobuf:"varint,6,opt,name=trophies_delta_side_2,json=trophiesDeltaSide2,proto3" json:"trophies_delta_side_2,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BattleResultPush) Reset() {
	*x = BattleResultPush{}
	mi := &file_battle_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleResultPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleResultPush) ProtoMessage() {}

func (x *BattleResultPush) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleResultPush.ProtoReflect.Descriptor instead.
func (*BattleResultPush) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{7}
}

func (x *BattleResultPush) GetWinner() BattleResultPush_Winner {
	if x != nil {
		return x.Winner
	}
	return BattleResultPush_DRAW
}

func (x *BattleResultPush) GetReason() BattleResultPush_Reason {
	if x != nil {
		return x.Reason
	}
	return BattleResultPush_REASON_UNKNOWN
}

func (x *BattleResultPush) GetSide_1Score() int32 {
	if x != nil {
		return x.Side_1Score
	}
	return 0
}

func (x *BattleResultPush) GetSide_2Score() int32 {
	if x != nil {
		return x.Side_2Score
	}
	return 0
}

func (x *BattleResultPush) GetTrophiesDeltaSide_1() int32 {
	if x != nil {
		return x.TrophiesDeltaSide_1
	}
	return 0
}

func (x *BattleResultPush) GetTrophiesDeltaSide_2() int32 {
	if x != nil {
		return x.TrophiesDeltaSide_2
	}
	return 0
}

// 战斗内心跳，60s 无心跳 -> 判定断线超时认输。
type HeartbeatPing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientTime    int64                  `protobuf:"varint,1,opt,name=client_time,json=clientTime,proto3" json:"client_time,omitempty"` // unix millis（用于 RTT 估算）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatPing) Reset() {
	*x = HeartbeatPing{}
	mi := &file_battle_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatPing) ProtoMessage() {}

func (x *HeartbeatPing) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatPing.ProtoReflect.Descriptor instead.
func (*HeartbeatPing) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{8}
}

func (x *HeartbeatPing) GetClientTime() int64 {
	if x != nil {
		return x.ClientTime
	}
	return 0
}

type HeartbeatPong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerTime    int64                  `protobuf:"varint,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"` // unix millis
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatPong) Reset() {
	*x = HeartbeatPong{}
	mi := &file_battle_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatPong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatPong) ProtoMessage() {}

func (x *HeartbeatPong) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatPong.ProtoReflect.Descriptor instead.
func (*HeartbeatPong) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{9}
}

func (x *HeartbeatPong) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

type TickBundle_SideDeploy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Side          int32                  `protobuf:"varint,1,opt,name=side,proto3" json:"side,omitempty"` // 1 或 2
	Deploy        *DeployCmd             `protobuf:"bytes,2,opt,name=deploy,proto3" json:"deploy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TickBundle_SideDeploy) Reset() {
	*x = TickBundle_SideDeploy{}
	mi := &file_battle_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TickBundle_SideDeploy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickBundle_SideDeploy) ProtoMessage() {}

func (x *TickBundle_SideDeploy) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickBundle_SideDeploy.ProtoReflect.Descriptor instead.
func (*TickBundle_SideDeploy) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{4, 0}
}

func (x *TickBundle_SideDeploy) GetSide() int32 {
	if x != nil {
		return x.Side
	}
	return 0
}

func (x *TickBundle_SideDeploy) GetDeploy() *DeployCmd {
	if x != nil {
		return x.Deploy
	}
	return nil
}

var File_battle_proto protoreflect.FileDescriptor

const file_battle_proto_rawDesc = "" +
	"\n" +
	"\fbattle.proto\x12\agame.v4\x1a\fcommon.proto\":\n" +
	"\vJoinRoomReq\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x12\n" +
	"\x04deck\x18\x02 \x03(\tR\x04deck\"Q\n" +
	"\fCardProgress\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\x12\x12\n" +
	"\x04rank\x18\x03 \x01(\x05R\x04rank\"\xf8\x02\n" +
	"\fJoinRoomResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x123\n" +
	"\bopponent\x18\x02 \x01(\v2\x17.game.v4.ProfileSummaryR\bopponent\x12\x1b\n" +
	"\tyour_side\x18\x03 \x01(\x05R\byourSide\x12\x1d\n" +
	"\n" +
	"start_tick\x18\x04 \x01(\x05R\tstartTick\x12\x12\n" +
	"\x04seed\x18\x05 \x01(\x04R\x04seed\x12\x1d\n" +
	"\n" +
	"side1_deck\x18\x06 \x03(\tR\tside1Deck\x12\x1d\n" +
	"\n" +
	"side2_deck\x18\a \x03(\tR\tside2Deck\x12\x19\n" +
	"\blevel_id\x18\b \x01(\tR\alevelId\x12<\n" +
	"\x0eside1_progress\x18\t \x03(\v2\x15.game.v4.CardProgressR\rside1Progress\x12<\n" +
	"\x0eside2_progress\x18\n" +
	" \x03(\v2\x15.game.v4.CardProgressR\rside2Progress\"j\n" +
	"\tDeployCmd\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\x05R\x04tick\x12\x17\n" +
	"\acard_id\x18\x02 \x01(\tR\x06cardId\x12\x17\n" +
	"\ax_milli\x18\x03 \x01(\x05R\x06xMilli\x12\x17\n" +
	"\ay_milli\x18\x04 \x01(\x05R\x06yMilli\"\xa8\x01\n" +
	"\n" +
	"TickBundle\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\x05R\x04tick\x128\n" +
	"\adeploys\x18\x02 \x03(\v2\x1e.game.v4.TickBundle.SideDeployR\adeploys\x1aL\n" +
	"\n" +
	"SideDeploy\x12\x12\n" +
	"\x04side\x18\x01 \x01(\x05R\x04side\x12*\n" +
	"\x06deploy\x18\x02 \x01(\v2\x12.game.v4.DeployCmdR\x06deploy\"5\n" +
	"\vStateHashUp\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\x05R\x04tick\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\fR\x04hash\"\x99\x01\n" +
	"\x0fBattleEndReport\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\x05R\x04tick\x12\x16\n" +
	"\x06winner\x18\x02 \x01(\x05R\x06winner\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\x05R\x06reason\x12 \n" +
	"\fside_1_score\x18\x04 \x01(\x05R\n" +
	"side1Score\x12 \n" +
	"\fside_2_score\x18\x05 \x01(\x05R\n" +
	"side2Score\"\xcf\x03\n" +
	"\x10BattleResultPush\x128\n" +
	"\x06winner\x18\x01 \x01(\x0e2 .game.v4.BattleResultPush.WinnerR\x06winner\x128\n" +
	"\x06reason\x18\x02 \x01(\x0e2 .game.v4.BattleResultPush.ReasonR\x06reason\x12 \n" +
	"\fside_1_score\x18\x03 \x01(\x05R\n" +
	"side1Score\x12 \n" +
	"\fside_2_score\x18\x04 \x01(\x05R\n" +
	"side2Score\x121\n" +
	"\x15trophies_delta_side_1\x18\x05 \x01(\x05R\x12trophiesDeltaSide1\x121\n" +
	"\x15trophies_delta_side_2\x18\x06 \x01(\x05R\x12trophiesDeltaSide2\"*\n" +
	"\x06Winner\x12\b\n" +
	"\x04DRAW\x10\x00\x12\n" +
	"\n" +
	"\x06SIDE_1\x10\x01\x12\n" +
	"\n" +
	"\x06SIDE_2\x10\x02\"q\n" +
	"\x06Reason\x12\x12\n" +
	"\x0eREASON_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eKING_DESTROYED\x10\x01\x12\v\n" +
	"\aTIMEOUT\x10\x02\x12\r\n" +
	"\tSURRENDER\x10\x03\x12\x0e\n" +
	"\n" +
	"DISCONNECT\x10\x04\x12\x13\n" +
	"\x0fHASH_DIVERGENCE\x10\x05\"0\n" +
	"\rHeartbeatPing\x12\x1f\n" +
	"\vclient_time\x18\x01 \x01(\x03R\n" +
	"clientTime\"0\n" +
	"\rHeartbeatPong\x12\x1f\n" +
	"\vserver_time\x18\x01 \x01(\x03R\n" +
	"serverTimeBAZ?github.com/jchensh/godot-clash-pusher/server/internal/pb/battleb\x06proto3"

var (
	file_battle_proto_rawDescOnce sync.Once
	file_battle_proto_rawDescData []byte
)

func file_battle_proto_rawDescGZIP() []byte {
	file_battle_proto_rawDescOnce.Do(func() {
		file_battle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_battle_proto_rawDesc), len(file_battle_proto_rawDesc)))
	})
	return file_battle_proto_rawDescData
}

var file_battle_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_battle_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_battle_proto_goTypes = []any{
	(BattleResultPush_Winner)(0),  // 0: game.v4.BattleResultPush.Winner
	(BattleResultPush_Reason)(0),  // 1: game.v4.BattleResultPush.Reason
	(*JoinRoomReq)(nil),           // 2: game.v4.JoinRoomReq
	(*CardProgress)(nil),          // 3: game.v4.CardProgress
	(*JoinRoomResp)(nil),          // 4: game.v4.JoinRoomResp
	(*DeployCmd)(nil),             // 5: game.v4.DeployCmd
	(*TickBundle)(nil),            // 6: game.v4.TickBundle
	(*StateHashUp)(nil),           // 7: game.v4.StateHashUp
	(*BattleEndReport)(nil),       // 8: game.v4.BattleEndReport
	(*BattleResultPush)(nil),      // 9: game.v4.BattleResultPush
	(*HeartbeatPing)(nil),         // 10: game.v4.HeartbeatPing
	(*HeartbeatPong)(nil),         // 11: game.v4.HeartbeatPong
	(*TickBundle_SideDeploy)(nil), // 12: game.v4.TickBundle.SideDeploy
	(*common.ProfileSummary)(nil), // 13: game.v4.ProfileSummary
}
var file_battle_proto_depIdxs = []int32{
	13, // 0: game.v4.JoinRoomResp.opponent:type_name -> game.v4.ProfileSummary
	3,  // 1: game.v4.JoinRoomResp.side1_progress:type_name -> game.v4.CardProgress
	3,  // 2: game.v4.JoinRoomResp.side2_progress:type_name -> game.v4.CardProgress
	12, // 3: game.v4.TickBundle.deploys:type_name -> game.v4.TickBundle.SideDeploy
	0,  // 4: game.v4.BattleResultPush.winner:type_name -> game.v4.BattleResultPush.Winner
	1,  // 5: game.v4.BattleResultPush.reason:type_name -> game.v4.BattleResultPush.Reason
	5,  // 6: game.v4.TickBundle.SideDeploy.deploy:type_name -> game.v4.DeployCmd
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_battle_proto_init() }
func file_battle_proto_init() {
	if File_battle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_battle_proto_rawDesc), len(file_battle_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_battle_proto_goTypes,
		DependencyIndexes: file_battle_proto_depIdxs,
		EnumInfos:         file_battle_proto_enumTypes,
		MessageInfos:      file_battle_proto_msgTypes,
	}.Build()
	File_battle_proto = out.File
	file_battle_proto_goTypes = nil
	file_battle_proto_depIdxs = nil
}
