// kingdom.proto — 王国领地系统（K1，DESIGN_KINGDOM.md；决策 48 服务器权威）。
//
// HTTP（api:8080，Bearer 会话令牌）：
//   GET  /v5/kingdom/state     → KingdomState
//   POST /v5/kingdom/upgrade   KingdomActionReq{building} → KingdomState（Lv0→1 即建造，统一动作）
//   POST /v5/kingdom/collect   KingdomActionReq{}         → KingdomState（收取全部产出）
//   POST /v5/kingdom/speedup   KingdomActionReq{building} → KingdomState（宝石加速完成施工）
// 成本/上限/产出/计时全在服务器用服务器侧配置 + 服务器时钟算（改本地无效）；
// 客户端只收发数据 + 展示（用户拍板 2026-07-19：服务器权威为永久原则）。
// 扩展性：资源用 repeated KV（不用 map——godobuf 兼容性保守），新资源/新建筑 = 配置扩展零 proto 改动。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: kingdom.proto

package kingdom

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 通用资源量 KV（food/wood/... 未来新货币直接复用）。
type ResourceAmount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceAmount) Reset() {
	*x = ResourceAmount{}
	mi := &file_kingdom_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceAmount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceAmount) ProtoMessage() {}

func (x *ResourceAmount) ProtoReflect() protoreflect.Message {
	mi := &file_kingdom_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceAmount.ProtoReflect.Descriptor instead.
func (*ResourceAmount) Descriptor() ([]byte, []int) {
	return file_kingdom_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceAmount) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *ResourceAmount) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type KingdomBuilding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Building      string                 `protobuf:"bytes,1,opt,name=building,proto3" json:"building,omitempty"`                                // 配置键：keep/farm/workshop/granary/wall/watchtower/mint/...
	Level         int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`                                     // 0 = 未建造
	UpgradeEndTs  int64                  `protobuf:"varint,3,opt,name=upgrade_end_ts,json=upgradeEndTs,proto3" json:"upgrade_end_ts,omitempty"` // >0 = 施工中，服务器时钟到点后任意读写自动完级
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KingdomBuilding) Reset() {
	*x = KingdomBuilding{}
	mi := &file_kingdom_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KingdomBuilding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KingdomBuilding) ProtoMessage() {}

func (x *KingdomBuilding) ProtoReflect() protoreflect.Message {
	mi := &file_kingdom_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KingdomBuilding.ProtoReflect.Descriptor instead.
func (*KingdomBuilding) Descriptor() ([]byte, []int) {
	return file_kingdom_proto_rawDescGZIP(), []int{1}
}

func (x *KingdomBuilding) GetBuilding() string {
	if x != nil {
		return x.Building
	}
	return ""
}

func (x *KingdomBuilding) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *KingdomBuilding) GetUpgradeEndTs() int64 {
	if x != nil {
		return x.UpgradeEndTs
	}
	return 0
}

type KingdomState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resources     []*ResourceAmount      `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"` // 王国仓内资源现量
	Buildings     []*KingdomBuilding     `protobuf:"bytes,2,rep,name=buildings,proto3" json:"buildings,omitempty"`
	ServerNowTs   int64                  `protobuf:"varint,3,opt,name=server_now_ts,json=serverNowTs,proto3" json:"server_now_ts,omitempty"` // 客户端倒计时/产量预估的唯一时间基准
	Pending       []*ResourceAmount      `protobuf:"bytes,4,rep,name=pending,proto3" json:"pending,omitempty"`                               // 各资源可收取量（服务器算好，client 只显示）
	PendingGold   int64                  `protobuf:"varint,5,opt,name=pending_gold,json=pendingGold,proto3" json:"pending_gold,omitempty"`   // 铸币坊可收金币（进主钱包，单列便于展示）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KingdomState) Reset() {
	*x = KingdomState{}
	mi := &file_kingdom_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KingdomState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KingdomState) ProtoMessage() {}

func (x *KingdomState) ProtoReflect() protoreflect.Message {
	mi := &file_kingdom_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KingdomState.ProtoReflect.Descriptor instead.
func (*KingdomState) Descriptor() ([]byte, []int) {
	return file_kingdom_proto_rawDescGZIP(), []int{2}
}

func (x *KingdomState) GetResources() []*ResourceAmount {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *KingdomState) GetBuildings() []*KingdomBuilding {
	if x != nil {
		return x.Buildings
	}
	return nil
}

func (x *KingdomState) GetServerNowTs() int64 {
	if x != nil {
		return x.ServerNowTs
	}
	return 0
}

func (x *KingdomState) GetPending() []*ResourceAmount {
	if x != nil {
		return x.Pending
	}
	return nil
}

func (x *KingdomState) GetPendingGold() int64 {
	if x != nil {
		return x.PendingGold
	}
	return 0
}

// upgrade / speedup 用 building；collect 忽略该字段（收取全部）。
type KingdomActionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Building      string                 `protobuf:"bytes,1,opt,name=building,proto3" json:"building,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KingdomActionReq) Reset() {
	*x = KingdomActionReq{}
	mi := &file_kingdom_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KingdomActionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KingdomActionReq) ProtoMessage() {}

func (x *KingdomActionReq) ProtoReflect() protoreflect.Message {
	mi := &file_kingdom_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KingdomActionReq.ProtoReflect.Descriptor instead.
func (*KingdomActionReq) Descriptor() ([]byte, []int) {
	return file_kingdom_proto_rawDescGZIP(), []int{3}
}

func (x *KingdomActionReq) GetBuilding() string {
	if x != nil {
		return x.Building
	}
	return ""
}

var File_kingdom_proto protoreflect.FileDescriptor

const file_kingdom_proto_rawDesc = "" +
	"\n" +
	"\rkingdom.proto\x12\agame.v4\"D\n" +
	"\x0eResourceAmount\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\"i\n" +
	"\x0fKingdomBuilding\x12\x1a\n" +
	"\bbuilding\x18\x01 \x01(\tR\bbuilding\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\x12$\n" +
	"\x0eupgrade_end_ts\x18\x03 \x01(\x03R\fupgradeEndTs\"\xf7\x01\n" +
	"\fKingdomState\x125\n" +
	"\tresources\x18\x01 \x03(\v2\x17.game.v4.ResourceAmountR\tresources\x126\n" +
	"\tbuildings\x18\x02 \x03(\v2\x18.game.v4.KingdomBuildingR\tbuildings\x12\"\n" +
	"\rserver_now_ts\x18\x03 \x01(\x03R\vserverNowTs\x121\n" +
	"\apending\x18\x04 \x03(\v2\x17.game.v4.ResourceAmountR\apending\x12!\n" +
	"\fpending_gold\x18\x05 \x01(\x03R\vpendingGold\".\n" +
	"\x10KingdomActionReq\x12\x1a\n" +
	"\bbuilding\x18\x01 \x01(\tR\bbuildingBBZ@github.com/jchensh/godot-clash-pusher/server/internal/pb/kingdomb\x06proto3"

var (
	file_kingdom_proto_rawDescOnce sync.Once
	file_kingdom_proto_rawDescData []byte
)

func file_kingdom_proto_rawDescGZIP() []byte {
	file_kingdom_proto_rawDescOnce.Do(func() {
		file_kingdom_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kingdom_proto_rawDesc), len(file_kingdom_proto_rawDesc)))
	})
	return file_kingdom_proto_rawDescData
}

var file_kingdom_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_kingdom_proto_goTypes = []any{
	(*ResourceAmount)(nil),   // 0: game.v4.ResourceAmount
	(*KingdomBuilding)(nil),  // 1: game.v4.KingdomBuilding
	(*KingdomState)(nil),     // 2: game.v4.KingdomState
	(*KingdomActionReq)(nil), // 3: game.v4.KingdomActionReq
}
var file_kingdom_proto_depIdxs = []int32{
	0, // 0: game.v4.KingdomState.resources:type_name -> game.v4.ResourceAmount
	1, // 1: game.v4.KingdomState.buildings:type_name -> game.v4.KingdomBuilding
	0, // 2: game.v4.KingdomState.pending:type_name -> game.v4.ResourceAmount
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_kingdom_proto_init() }
func file_kingdom_proto_init() {
	if File_kingdom_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kingdom_proto_rawDesc), len(file_kingdom_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kingdom_proto_goTypes,
		DependencyIndexes: file_kingdom_proto_depIdxs,
		MessageInfos:      file_kingdom_proto_msgTypes,
	}.Build()
	File_kingdom_proto = out.File
	file_kingdom_proto_goTypes = nil
	file_kingdom_proto_depIdxs = nil
}
