// common.proto — V4 wire 层共享消息 ID 枚举 + 通用错误 + 帧格式说明
//
// WS frame 约定：[2 bytes msg_id (big-endian uint16)][N bytes protobuf payload]
//   - msg_id 取自下面的 MsgId 枚举
//   - PING/PONG 无 payload（payload N=0）
//   - 所有 req/resp 严格对应：客户端发 *_REQ，服务端回 *_RESP；服务端主动推用 *_PUSH

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 消息 ID 枚举，分段：0-9 = 心跳/错误，10-19 = auth，20-29 = profile，
// 30-39 = match (lobby)，40-49 = battle，50-59 = leaderboard，60-69 = V5 会话/经济（决策 48）。
// 新增消息按段尾追加，**不复用**已用过的 id。
type MsgId int32

const (
	MsgId_MSG_UNKNOWN               MsgId = 0
	MsgId_PING                      MsgId = 1
	MsgId_PONG                      MsgId = 2
	MsgId_ERROR_RESP                MsgId = 3
	MsgId_LOGIN_REQ                 MsgId = 10
	MsgId_LOGIN_RESP                MsgId = 11
	MsgId_REFRESH_REQ               MsgId = 12
	MsgId_REFRESH_RESP              MsgId = 13
	MsgId_PROFILE_GET_REQ           MsgId = 20
	MsgId_PROFILE_GET_RESP          MsgId = 21
	MsgId_DECK_UPDATE_REQ           MsgId = 22
	MsgId_DECK_UPDATE_RESP          MsgId = 23
	MsgId_PROFILE_UPDATE_REQ        MsgId = 24 // V5-S9：改昵称/头像
	MsgId_PROFILE_UPDATE_RESP       MsgId = 25
	MsgId_PROFILE_TUTORIAL_DONE_REQ MsgId = 26 // V5-S9：标记新手引导已完成
	MsgId_FIND_MATCH_REQ            MsgId = 30
	MsgId_FIND_MATCH_RESP           MsgId = 31
	MsgId_CANCEL_MATCH_REQ          MsgId = 32
	MsgId_CANCEL_MATCH_RESP         MsgId = 33
	MsgId_MATCH_FOUND_PUSH          MsgId = 34
	MsgId_JOIN_ROOM_REQ             MsgId = 40
	MsgId_JOIN_ROOM_RESP            MsgId = 41
	MsgId_DEPLOY_CMD                MsgId = 42
	MsgId_TICK_BUNDLE               MsgId = 43
	MsgId_STATE_HASH_UP             MsgId = 44
	MsgId_BATTLE_RESULT_PUSH        MsgId = 45
	MsgId_HEARTBEAT_PING            MsgId = 46
	MsgId_HEARTBEAT_PONG            MsgId = 47
	MsgId_BATTLE_END_REPORT         MsgId = 48 // 客户端 -> 服务端：本地 sim 判定对局结束（lockstep 服务端无 sim，靠两端上报）
	MsgId_LEADERBOARD_TOP_REQ       MsgId = 50
	MsgId_LEADERBOARD_TOP_RESP      MsgId = 51
	// 60-69 = V5 会话/经济（决策 48）
	MsgId_CONFIG_PUSH              MsgId = 60 // server->client：登录后配置下发（V5-N2）
	MsgId_ECONOMY_STATE_REQ        MsgId = 61 // V5-N3 client->server：拉经济状态
	MsgId_ECONOMY_STATE_RESP       MsgId = 62 // V5-N3 server->client：经济状态
	MsgId_ECONOMY_UPGRADE_REQ      MsgId = 63 // V5-N4：升级
	MsgId_ECONOMY_RANK_UP_REQ      MsgId = 64 // V5-N4：升阶
	MsgId_ECONOMY_UNLOCK_REQ       MsgId = 65 // V5-N4：解锁
	MsgId_ECONOMY_STAGE_CLEAR_REQ  MsgId = 66 // V5-N5：通关上报（stage_id, stars）
	MsgId_ECONOMY_COLLECT_IDLE_REQ MsgId = 67 // V5-N6：挂机领取（now 全服务器定）
	MsgId_PVE_START_REQ            MsgId = 68 // KAN-78：PVE 开战报到（服务器时钟记 started_at + 养成快照）
	MsgId_PVE_REPORT_REQ           MsgId = 69 // KAN-79：PVE 指令流/哈希周期批量上报（时序真实性）
	MsgId_KINGDOM_STATE_REQ        MsgId = 70 // K1（DESIGN_KINGDOM）client->server：拉王国状态
	MsgId_KINGDOM_STATE_RESP       MsgId = 71 // K1 server->client：王国状态（含 server_now/pending）
	MsgId_KINGDOM_UPGRADE_REQ      MsgId = 72 // K1：建造/升级（Lv0→1 即建造，统一动作）
	MsgId_KINGDOM_COLLECT_REQ      MsgId = 73 // K1：收取全部产出（服务器时钟结算）
	MsgId_KINGDOM_SPEEDUP_REQ      MsgId = 74 // K1：宝石加速完成施工
)

// Enum value maps for MsgId.
var (
	MsgId_name = map[int32]string{
		0:  "MSG_UNKNOWN",
		1:  "PING",
		2:  "PONG",
		3:  "ERROR_RESP",
		10: "LOGIN_REQ",
		11: "LOGIN_RESP",
		12: "REFRESH_REQ",
		13: "REFRESH_RESP",
		20: "PROFILE_GET_REQ",
		21: "PROFILE_GET_RESP",
		22: "DECK_UPDATE_REQ",
		23: "DECK_UPDATE_RESP",
		24: "PROFILE_UPDATE_REQ",
		25: "PROFILE_UPDATE_RESP",
		26: "PROFILE_TUTORIAL_DONE_REQ",
		30: "FIND_MATCH_REQ",
		31: "FIND_MATCH_RESP",
		32: "CANCEL_MATCH_REQ",
		33: "CANCEL_MATCH_RESP",
		34: "MATCH_FOUND_PUSH",
		40: "JOIN_ROOM_REQ",
		41: "JOIN_ROOM_RESP",
		42: "DEPLOY_CMD",
		43: "TICK_BUNDLE",
		44: "STATE_HASH_UP",
		45: "BATTLE_RESULT_PUSH",
		46: "HEARTBEAT_PING",
		47: "HEARTBEAT_PONG",
		48: "BATTLE_END_REPORT",
		50: "LEADERBOARD_TOP_REQ",
		51: "LEADERBOARD_TOP_RESP",
		60: "CONFIG_PUSH",
		61: "ECONOMY_STATE_REQ",
		62: "ECONOMY_STATE_RESP",
		63: "ECONOMY_UPGRADE_REQ",
		64: "ECONOMY_RANK_UP_REQ",
		65: "ECONOMY_UNLOCK_REQ",
		66: "ECONOMY_STAGE_CLEAR_REQ",
		67: "ECONOMY_COLLECT_IDLE_REQ",
		68: "PVE_START_REQ",
		69: "PVE_REPORT_REQ",
		70: "KINGDOM_STATE_REQ",
		71: "KINGDOM_STATE_RESP",
		72: "KINGDOM_UPGRADE_REQ",
		73: "KINGDOM_COLLECT_REQ",
		74: "KINGDOM_SPEEDUP_REQ",
	}
	MsgId_value = map[string]int32{
		"MSG_UNKNOWN":               0,
		"PING":                      1,
		"PONG":                      2,
		"ERROR_RESP":                3,
		"LOGIN_REQ":                 10,
		"LOGIN_RESP":                11,
		"REFRESH_REQ":               12,
		"REFRESH_RESP":              13,
		"PROFILE_GET_REQ":           20,
		"PROFILE_GET_RESP":          21,
		"DECK_UPDATE_REQ":           22,
		"DECK_UPDATE_RESP":          23,
		"PROFILE_UPDATE_REQ":        24,
		"PROFILE_UPDATE_RESP":       25,
		"PROFILE_TUTORIAL_DONE_REQ": 26,
		"FIND_MATCH_REQ":            30,
		"FIND_MATCH_RESP":           31,
		"CANCEL_MATCH_REQ":          32,
		"CANCEL_MATCH_RESP":         33,
		"MATCH_FOUND_PUSH":          34,
		"JOIN_ROOM_REQ":             40,
		"JOIN_ROOM_RESP":            41,
		"DEPLOY_CMD":                42,
		"TICK_BUNDLE":               43,
		"STATE_HASH_UP":             44,
		"BATTLE_RESULT_PUSH":        45,
		"HEARTBEAT_PING":            46,
		"HEARTBEAT_PONG":            47,
		"BATTLE_END_REPORT":         48,
		"LEADERBOARD_TOP_REQ":       50,
		"LEADERBOARD_TOP_RESP":      51,
		"CONFIG_PUSH":               60,
		"ECONOMY_STATE_REQ":         61,
		"ECONOMY_STATE_RESP":        62,
		"ECONOMY_UPGRADE_REQ":       63,
		"ECONOMY_RANK_UP_REQ":       64,
		"ECONOMY_UNLOCK_REQ":        65,
		"ECONOMY_STAGE_CLEAR_REQ":   66,
		"ECONOMY_COLLECT_IDLE_REQ":  67,
		"PVE_START_REQ":             68,
		"PVE_REPORT_REQ":            69,
		"KINGDOM_STATE_REQ":         70,
		"KINGDOM_STATE_RESP":        71,
		"KINGDOM_UPGRADE_REQ":       72,
		"KINGDOM_COLLECT_REQ":       73,
		"KINGDOM_SPEEDUP_REQ":       74,
	}
)

func (x MsgId) Enum() *MsgId {
	p := new(MsgId)
	*p = x
	return p
}

func (x MsgId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgId) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (MsgId) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x MsgId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgId.Descriptor instead.
func (MsgId) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

// 通用错误码。前 1000 为框架级（鉴权/限流），1000+ 为业务级（按模块分段）。
type ErrorCode int32

const (
	ErrorCode_ERR_OK                       ErrorCode = 0
	ErrorCode_ERR_INTERNAL                 ErrorCode = 1
	ErrorCode_ERR_INVALID_ARG              ErrorCode = 2
	ErrorCode_ERR_UNAUTHORIZED             ErrorCode = 3
	ErrorCode_ERR_RATE_LIMITED             ErrorCode = 4
	ErrorCode_ERR_NOT_FOUND                ErrorCode = 5
	ErrorCode_ERR_AUTH_INVALID_TOKEN       ErrorCode = 100
	ErrorCode_ERR_AUTH_EXPIRED             ErrorCode = 101
	ErrorCode_ERR_AUTH_BANNED              ErrorCode = 102
	ErrorCode_ERR_PROFILE_VERSION_MISMATCH ErrorCode = 200
	ErrorCode_ERR_PROFILE_DECK_INVALID     ErrorCode = 201
	ErrorCode_ERR_MATCH_ALREADY_QUEUED     ErrorCode = 300
	ErrorCode_ERR_MATCH_NOT_QUEUED         ErrorCode = 301
	ErrorCode_ERR_BATTLE_ROOM_NOT_FOUND    ErrorCode = 400
	ErrorCode_ERR_BATTLE_INVALID_DEPLOY    ErrorCode = 401
	ErrorCode_ERR_BATTLE_HASH_MISMATCH     ErrorCode = 402
	ErrorCode_ERR_ECONOMY_INSUFFICIENT     ErrorCode = 500 // V5-N4：金币/碎片不足
	ErrorCode_ERR_ECONOMY_AT_CAP           ErrorCode = 501 // V5-N4：已达等级/阶上限
	ErrorCode_ERR_ECONOMY_LOCKED           ErrorCode = 502 // V5-N4：卡未解锁 / 不满足解锁条件
	ErrorCode_ERR_ECONOMY_STAGE_LOCKED     ErrorCode = 503 // V5-N5：关卡未解锁（进度不连续/前一关未通关）
	ErrorCode_ERR_PVE_BATTLE_INVALID       ErrorCode = 504 // KAN-78：PVE 战斗会话无效（battle_id 不存在/不属己/
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:   "ERR_OK",
		1:   "ERR_INTERNAL",
		2:   "ERR_INVALID_ARG",
		3:   "ERR_UNAUTHORIZED",
		4:   "ERR_RATE_LIMITED",
		5:   "ERR_NOT_FOUND",
		100: "ERR_AUTH_INVALID_TOKEN",
		101: "ERR_AUTH_EXPIRED",
		102: "ERR_AUTH_BANNED",
		200: "ERR_PROFILE_VERSION_MISMATCH",
		201: "ERR_PROFILE_DECK_INVALID",
		300: "ERR_MATCH_ALREADY_QUEUED",
		301: "ERR_MATCH_NOT_QUEUED",
		400: "ERR_BATTLE_ROOM_NOT_FOUND",
		401: "ERR_BATTLE_INVALID_DEPLOY",
		402: "ERR_BATTLE_HASH_MISMATCH",
		500: "ERR_ECONOMY_INSUFFICIENT",
		501: "ERR_ECONOMY_AT_CAP",
		502: "ERR_ECONOMY_LOCKED",
		503: "ERR_ECONOMY_STAGE_LOCKED",
		504: "ERR_PVE_BATTLE_INVALID",
	}
	ErrorCode_value = map[string]int32{
		"ERR_OK":                       0,
		"ERR_INTERNAL":                 1,
		"ERR_INVALID_ARG":              2,
		"ERR_UNAUTHORIZED":             3,
		"ERR_RATE_LIMITED":             4,
		"ERR_NOT_FOUND":                5,
		"ERR_AUTH_INVALID_TOKEN":       100,
		"ERR_AUTH_EXPIRED":             101,
		"ERR_AUTH_BANNED":              102,
		"ERR_PROFILE_VERSION_MISMATCH": 200,
		"ERR_PROFILE_DECK_INVALID":     201,
		"ERR_MATCH_ALREADY_QUEUED":     300,
		"ERR_MATCH_NOT_QUEUED":         301,
		"ERR_BATTLE_ROOM_NOT_FOUND":    400,
		"ERR_BATTLE_INVALID_DEPLOY":    401,
		"ERR_BATTLE_HASH_MISMATCH":     402,
		"ERR_ECONOMY_INSUFFICIENT":     500,
		"ERR_ECONOMY_AT_CAP":           501,
		"ERR_ECONOMY_LOCKED":           502,
		"ERR_ECONOMY_STAGE_LOCKED":     503,
		"ERR_PVE_BATTLE_INVALID":       504,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[1].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[1]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

// 通用错误响应；当 server 处理 *_REQ 失败时回此，msg_id=ERROR_RESP。
type ErrorResp struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Code   ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=game.v4.ErrorCode" json:"code,omitempty"`
	Detail string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"` // 人类可读错误描述（不直接暴露给用户，给开发看）
	// 注：原名是 message，但 godobuf 把它当 proto 保留字
	InReplyTo     MsgId `protobuf:"varint,3,opt,name=in_reply_to,json=inReplyTo,proto3,enum=game.v4.MsgId" json:"in_reply_to,omitempty"` // 哪个 req 出错（便于客户端关联）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResp) Reset() {
	*x = ErrorResp{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResp) ProtoMessage() {}

func (x *ErrorResp) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResp.ProtoReflect.Descriptor instead.
func (*ErrorResp) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorResp) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERR_OK
}

func (x *ErrorResp) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *ErrorResp) GetInReplyTo() MsgId {
	if x != nil {
		return x.InReplyTo
	}
	return MsgId_MSG_UNKNOWN
}

// 玩家简要信息，多处复用（match found、battle join、leaderboard 等）。
type ProfileSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	AvatarId      int32                  `protobuf:"varint,3,opt,name=avatar_id,json=avatarId,proto3" json:"avatar_id,omitempty"`
	Level         int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	Trophies      int32                  `protobuf:"varint,5,opt,name=trophies,proto3" json:"trophies,omitempty"`
	AvatarCardId  string                 `protobuf:"bytes,6,opt,name=avatar_card_id,json=avatarCardId,proto3" json:"avatar_card_id,omitempty"` // V5-S9：头像=怪物卡 id（PVP 对手名片用）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileSummary) Reset() {
	*x = ProfileSummary{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileSummary) ProtoMessage() {}

func (x *ProfileSummary) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileSummary.ProtoReflect.Descriptor instead.
func (*ProfileSummary) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *ProfileSummary) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *ProfileSummary) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *ProfileSummary) GetAvatarId() int32 {
	if x != nil {
		return x.AvatarId
	}
	return 0
}

func (x *ProfileSummary) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *ProfileSummary) GetTrophies() int32 {
	if x != nil {
		return x.Trophies
	}
	return 0
}

func (x *ProfileSummary) GetAvatarCardId() string {
	if x != nil {
		return x.AvatarCardId
	}
	return ""
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\agame.v4\"{\n" +
	"\tErrorResp\x12&\n" +
	"\x04code\x18\x01 \x01(\x0e2\x12.game.v4.ErrorCodeR\x04code\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\x12.\n" +
	"\vin_reply_to\x18\x03 \x01(\x0e2\x0e.game.v4.MsgIdR\tinReplyTo\"\xc0\x01\n" +
	"\x0eProfileSummary\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x1b\n" +
	"\tavatar_id\x18\x03 \x01(\x05R\bavatarId\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\x12\x1a\n" +
	"\btrophies\x18\x05 \x01(\x05R\btrophies\x12$\n" +
	"\x0eavatar_card_id\x18\x06 \x01(\tR\favatarCardId*\xdb\a\n" +
	"\x05MsgId\x12\x0f\n" +
	"\vMSG_UNKNOWN\x10\x00\x12\b\n" +
	"\x04PING\x10\x01\x12\b\n" +
	"\x04PONG\x10\x02\x12\x0e\n" +
	"\n" +
	"ERROR_RESP\x10\x03\x12\r\n" +
	"\tLOGIN_REQ\x10\n" +
	"\x12\x0e\n" +
	"\n" +
	"LOGIN_RESP\x10\v\x12\x0f\n" +
	"\vREFRESH_REQ\x10\f\x12\x10\n" +
	"\fREFRESH_RESP\x10\r\x12\x13\n" +
	"\x0fPROFILE_GET_REQ\x10\x14\x12\x14\n" +
	"\x10PROFILE_GET_RESP\x10\x15\x12\x13\n" +
	"\x0fDECK_UPDATE_REQ\x10\x16\x12\x14\n" +
	"\x10DECK_UPDATE_RESP\x10\x17\x12\x16\n" +
	"\x12PROFILE_UPDATE_REQ\x10\x18\x12\x17\n" +
	"\x13PROFILE_UPDATE_RESP\x10\x19\x12\x1d\n" +
	"\x19PROFILE_TUTORIAL_DONE_REQ\x10\x1a\x12\x12\n" +
	"\x0eFIND_MATCH_REQ\x10\x1e\x12\x13\n" +
	"\x0fFIND_MATCH_RESP\x10\x1f\x12\x14\n" +
	"\x10CANCEL_MATCH_REQ\x10 \x12\x15\n" +
	"\x11CANCEL_MATCH_RESP\x10!\x12\x14\n" +
	"\x10MATCH_FOUND_PUSH\x10\"\x12\x11\n" +
	"\rJOIN_ROOM_REQ\x10(\x12\x12\n" +
	"\x0eJOIN_ROOM_RESP\x10)\x12\x0e\n" +
	"\n" +
	"DEPLOY_CMD\x10*\x12\x0f\n" +
	"\vTICK_BUNDLE\x10+\x12\x11\n" +
	"\rSTATE_HASH_UP\x10,\x12\x16\n" +
	"\x12BATTLE_RESULT_PUSH\x10-\x12\x12\n" +
	"\x0eHEARTBEAT_PING\x10.\x12\x12\n" +
	"\x0eHEARTBEAT_PONG\x10/\x12\x15\n" +
	"\x11BATTLE_END_REPORT\x100\x12\x17\n" +
	"\x13LEADERBOARD_TOP_REQ\x102\x12\x18\n" +
	"\x14LEADERBOARD_TOP_RESP\x103\x12\x0f\n" +
	"\vCONFIG_PUSH\x10<\x12\x15\n" +
	"\x11ECONOMY_STATE_REQ\x10=\x12\x16\n" +
	"\x12ECONOMY_STATE_RESP\x10>\x12\x17\n" +
	"\x13ECONOMY_UPGRADE_REQ\x10?\x12\x17\n" +
	"\x13ECONOMY_RANK_UP_REQ\x10@\x12\x16\n" +
	"\x12ECONOMY_UNLOCK_REQ\x10A\x12\x1b\n" +
	"\x17ECONOMY_STAGE_CLEAR_REQ\x10B\x12\x1c\n" +
	"\x18ECONOMY_COLLECT_IDLE_REQ\x10C\x12\x11\n" +
	"\rPVE_START_REQ\x10D\x12\x12\n" +
	"\x0ePVE_REPORT_REQ\x10E\x12\x15\n" +
	"\x11KINGDOM_STATE_REQ\x10F\x12\x16\n" +
	"\x12KINGDOM_STATE_RESP\x10G\x12\x17\n" +
	"\x13KINGDOM_UPGRADE_REQ\x10H\x12\x17\n" +
	"\x13KINGDOM_COLLECT_REQ\x10I\x12\x17\n" +
	"\x13KINGDOM_SPEEDUP_REQ\x10J*\xac\x04\n" +
	"\tErrorCode\x12\n" +
	"\n" +
	"\x06ERR_OK\x10\x00\x12\x10\n" +
	"\fERR_INTERNAL\x10\x01\x12\x13\n" +
	"\x0fERR_INVALID_ARG\x10\x02\x12\x14\n" +
	"\x10ERR_UNAUTHORIZED\x10\x03\x12\x14\n" +
	"\x10ERR_RATE_LIMITED\x10\x04\x12\x11\n" +
	"\rERR_NOT_FOUND\x10\x05\x12\x1a\n" +
	"\x16ERR_AUTH_INVALID_TOKEN\x10d\x12\x14\n" +
	"\x10ERR_AUTH_EXPIRED\x10e\x12\x13\n" +
	"\x0fERR_AUTH_BANNED\x10f\x12!\n" +
	"\x1cERR_PROFILE_VERSION_MISMATCH\x10\xc8\x01\x12\x1d\n" +
	"\x18ERR_PROFILE_DECK_INVALID\x10\xc9\x01\x12\x1d\n" +
	"\x18ERR_MATCH_ALREADY_QUEUED\x10\xac\x02\x12\x19\n" +
	"\x14ERR_MATCH_NOT_QUEUED\x10\xad\x02\x12\x1e\n" +
	"\x19ERR_BATTLE_ROOM_NOT_FOUND\x10\x90\x03\x12\x1e\n" +
	"\x19ERR_BATTLE_INVALID_DEPLOY\x10\x91\x03\x12\x1d\n" +
	"\x18ERR_BATTLE_HASH_MISMATCH\x10\x92\x03\x12\x1d\n" +
	"\x18ERR_ECONOMY_INSUFFICIENT\x10\xf4\x03\x12\x17\n" +
	"\x12ERR_ECONOMY_AT_CAP\x10\xf5\x03\x12\x17\n" +
	"\x12ERR_ECONOMY_LOCKED\x10\xf6\x03\x12\x1d\n" +
	"\x18ERR_ECONOMY_STAGE_LOCKED\x10\xf7\x03\x12\x1b\n" +
	"\x16ERR_PVE_BATTLE_INVALID\x10\xf8\x03BAZ?github.com/jchensh/godot-clash-pusher/server/internal/pb/commonb\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_proto_goTypes = []any{
	(MsgId)(0),             // 0: game.v4.MsgId
	(ErrorCode)(0),         // 1: game.v4.ErrorCode
	(*ErrorResp)(nil),      // 2: game.v4.ErrorResp
	(*ProfileSummary)(nil), // 3: game.v4.ProfileSummary
}
var file_common_proto_depIdxs = []int32{
	1, // 0: game.v4.ErrorResp.code:type_name -> game.v4.ErrorCode
	0, // 1: game.v4.ErrorResp.in_reply_to:type_name -> game.v4.MsgId
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
