// match.proto — 匹配（lobby 阶段）
//
// V4-S4：客户端发 FindMatchReq -> 入 Redis ZSET 段位队列 -> 服务端 ELO 窗口扫描 ->
// 配对后两端各推 MatchFoundPush -> 客户端跳战斗页用 room_id 调 JoinRoomReq（battle.proto）。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: match.proto

package match

import (
	common "github.com/jchensh/godot-clash-pusher/server/internal/pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindMatchReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeckSlot      int32                  `protobuf:"varint,1,opt,name=deck_slot,json=deckSlot,proto3" json:"deck_slot,omitempty"` // 用哪个卡组打（slot 1..3）
	Arena         int32                  `protobuf:"varint,2,opt,name=arena,proto3" json:"arena,omitempty"`                       // 段位/竞技场 id，影响匹配桶（V4-S4 起步全默认 1）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindMatchReq) Reset() {
	*x = FindMatchReq{}
	mi := &file_match_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindMatchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindMatchReq) ProtoMessage() {}

func (x *FindMatchReq) ProtoReflect() protoreflect.Message {
	mi := &file_match_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindMatchReq.ProtoReflect.Descriptor instead.
func (*FindMatchReq) Descriptor() ([]byte, []int) {
	return file_match_proto_rawDescGZIP(), []int{0}
}

func (x *FindMatchReq) GetDeckSlot() int32 {
	if x != nil {
		return x.DeckSlot
	}
	return 0
}

func (x *FindMatchReq) GetArena() int32 {
	if x != nil {
		return x.Arena
	}
	return 0
}

type FindMatchResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	QueueId       string                 `protobuf:"bytes,2,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"` // 进队成功后返回，用于 cancel
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindMatchResp) Reset() {
	*x = FindMatchResp{}
	mi := &file_match_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindMatchResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindMatchResp) ProtoMessage() {}

func (x *FindMatchResp) ProtoReflect() protoreflect.Message {
	mi := &file_match_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindMatchResp.ProtoReflect.Descriptor instead.
func (*FindMatchResp) Descriptor() ([]byte, []int) {
	return file_match_proto_rawDescGZIP(), []int{1}
}

func (x *FindMatchResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *FindMatchResp) GetQueueId() string {
	if x != nil {
		return x.QueueId
	}
	return ""
}

type CancelMatchReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueId       string                 `protobuf:"bytes,1,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelMatchReq) Reset() {
	*x = CancelMatchReq{}
	mi := &file_match_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelMatchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelMatchReq) ProtoMessage() {}

func (x *CancelMatchReq) ProtoReflect() protoreflect.Message {
	mi := &file_match_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelMatchReq.ProtoReflect.Descriptor instead.
func (*CancelMatchReq) Descriptor() ([]byte, []int) {
	return file_match_proto_rawDescGZIP(), []int{2}
}

func (x *CancelMatchReq) GetQueueId() string {
	if x != nil {
		return x.QueueId
	}
	return ""
}

type CancelMatchResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelMatchResp) Reset() {
	*x = CancelMatchResp{}
	mi := &file_match_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelMatchResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelMatchResp) ProtoMessage() {}

func (x *CancelMatchResp) ProtoReflect() protoreflect.Message {
	mi := &file_match_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelMatchResp.ProtoReflect.Descriptor instead.
func (*CancelMatchResp) Descriptor() ([]byte, []int) {
	return file_match_proto_rawDescGZIP(), []int{3}
}

func (x *CancelMatchResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// 服务端主动推：找到对手了，跳战斗页。
type MatchFoundPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"` // UUID
	Opponent      *common.ProfileSummary `protobuf:"bytes,2,opt,name=opponent,proto3" json:"opponent,omitempty"`
	YourSide      int32                  `protobuf:"varint,3,opt,name=your_side,json=yourSide,proto3" json:"your_side,omitempty"` // 1 = player A（地图下方）/ 2 = player B（上方）
	Arena         int32                  `protobuf:"varint,4,opt,name=arena,proto3" json:"arena,omitempty"`
	Seed          uint64                 `protobuf:"varint,5,opt,name=seed,proto3" json:"seed,omitempty"` // run 级确定性 seed（spawn 序 tie-break 等用）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchFoundPush) Reset() {
	*x = MatchFoundPush{}
	mi := &file_match_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchFoundPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchFoundPush) ProtoMessage() {}

func (x *MatchFoundPush) ProtoReflect() protoreflect.Message {
	mi := &file_match_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchFoundPush.ProtoReflect.Descriptor instead.
func (*MatchFoundPush) Descriptor() ([]byte, []int) {
	return file_match_proto_rawDescGZIP(), []int{4}
}

func (x *MatchFoundPush) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *MatchFoundPush) GetOpponent() *common.ProfileSummary {
	if x != nil {
		return x.Opponent
	}
	return nil
}

func (x *MatchFoundPush) GetYourSide() int32 {
	if x != nil {
		return x.YourSide
	}
	return 0
}

func (x *MatchFoundPush) GetArena() int32 {
	if x != nil {
		return x.Arena
	}
	return 0
}

func (x *MatchFoundPush) GetSeed() uint64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

var File_match_proto protoreflect.FileDescriptor

const file_match_proto_rawDesc = "" +
	"\n" +
	"\vmatch.proto\x12\agame.v4\x1a\fcommon.proto\"A\n" +
	"\fFindMatchReq\x12\x1b\n" +
	"\tdeck_slot\x18\x01 \x01(\x05R\bdeckSlot\x12\x14\n" +
	"\x05arena\x18\x02 \x01(\x05R\x05arena\":\n" +
	"\rFindMatchResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x19\n" +
	"\bqueue_id\x18\x02 \x01(\tR\aqueueId\"+\n" +
	"\x0eCancelMatchReq\x12\x19\n" +
	"\bqueue_id\x18\x01 \x01(\tR\aqueueId\"!\n" +
	"\x0fCancelMatchResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\xa5\x01\n" +
	"\x0eMatchFoundPush\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x123\n" +
	"\bopponent\x18\x02 \x01(\v2\x17.game.v4.ProfileSummaryR\bopponent\x12\x1b\n" +
	"\tyour_side\x18\x03 \x01(\x05R\byourSide\x12\x14\n" +
	"\x05arena\x18\x04 \x01(\x05R\x05arena\x12\x12\n" +
	"\x04seed\x18\x05 \x01(\x04R\x04seedB@Z>github.com/jchensh/godot-clash-pusher/server/internal/pb/matchb\x06proto3"

var (
	file_match_proto_rawDescOnce sync.Once
	file_match_proto_rawDescData []byte
)

func file_match_proto_rawDescGZIP() []byte {
	file_match_proto_rawDescOnce.Do(func() {
		file_match_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_match_proto_rawDesc), len(file_match_proto_rawDesc)))
	})
	return file_match_proto_rawDescData
}

var file_match_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_match_proto_goTypes = []any{
	(*FindMatchReq)(nil),          // 0: game.v4.FindMatchReq
	(*FindMatchResp)(nil),         // 1: game.v4.FindMatchResp
	(*CancelMatchReq)(nil),        // 2: game.v4.CancelMatchReq
	(*CancelMatchResp)(nil),       // 3: game.v4.CancelMatchResp
	(*MatchFoundPush)(nil),        // 4: game.v4.MatchFoundPush
	(*common.ProfileSummary)(nil), // 5: game.v4.ProfileSummary
}
var file_match_proto_depIdxs = []int32{
	5, // 0: game.v4.MatchFoundPush.opponent:type_name -> game.v4.ProfileSummary
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_match_proto_init() }
func file_match_proto_init() {
	if File_match_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_match_proto_rawDesc), len(file_match_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_match_proto_goTypes,
		DependencyIndexes: file_match_proto_depIdxs,
		MessageInfos:      file_match_proto_msgTypes,
	}.Build()
	File_match_proto = out.File
	file_match_proto_goTypes = nil
	file_match_proto_depIdxs = nil
}
